syntax = "proto3";

package sentinez.std.net.waf.v1;

import "sentinez/std/common/v1/options.proto";
import "sentinez/std/net/waf/v1/types.proto";

option go_package = "github.com/sentinez/sentinez/api/gen/go/sentinez/std/net/waf/v1;waf";

message Event {
  option (sentinez.std.common.v1.sntz_msg_opts).database_model = true;

  repeated int32 rule_ids = 1;
  repeated string severities = 2;
  repeated string messages = 3;
  string request_path = 4;
  int32 score = 5;
  string request_ip = 6;
  string request_domain = 7;
  string transaction_id = 8;
  int64 request_time = 9; // milisec
  Service service = 10;
  Action action = 11;
  string req_id_ref = 12;
}