// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: sentinez/apps/security/v1/shared.proto

/* eslint-disable */

export const protobufPackage = "sentinez.apps.security.v1";
