// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package edgebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type EdgeIpLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Ip        uint32
}

// LoadEdge returns the embedded CollectionSpec for Edge.
func LoadEdge() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EdgeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Edge: %w", err)
	}

	return spec, err
}

// LoadEdgeObjects loads Edge and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*EdgeObjects
//	*EdgePrograms
//	*EdgeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadEdgeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadEdge()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// EdgeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EdgeSpecs struct {
	EdgeProgramSpecs
	EdgeMapSpecs
	EdgeVariableSpecs
}

// EdgeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EdgeProgramSpecs struct {
	EdgeMain *ebpf.ProgramSpec `ebpf:"edge_main"`
}

// EdgeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EdgeMapSpecs struct {
	Blocklist   *ebpf.MapSpec `ebpf:"blocklist"`
	IpBandwidth *ebpf.MapSpec `ebpf:"ip_bandwidth"`
}

// EdgeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EdgeVariableSpecs struct {
}

// EdgeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadEdgeObjects or ebpf.CollectionSpec.LoadAndAssign.
type EdgeObjects struct {
	EdgePrograms
	EdgeMaps
	EdgeVariables
}

func (o *EdgeObjects) Close() error {
	return _EdgeClose(
		&o.EdgePrograms,
		&o.EdgeMaps,
	)
}

// EdgeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadEdgeObjects or ebpf.CollectionSpec.LoadAndAssign.
type EdgeMaps struct {
	Blocklist   *ebpf.Map `ebpf:"blocklist"`
	IpBandwidth *ebpf.Map `ebpf:"ip_bandwidth"`
}

func (m *EdgeMaps) Close() error {
	return _EdgeClose(
		m.Blocklist,
		m.IpBandwidth,
	)
}

// EdgeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadEdgeObjects or ebpf.CollectionSpec.LoadAndAssign.
type EdgeVariables struct {
}

// EdgePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadEdgeObjects or ebpf.CollectionSpec.LoadAndAssign.
type EdgePrograms struct {
	EdgeMain *ebpf.Program `ebpf:"edge_main"`
}

func (p *EdgePrograms) Close() error {
	return _EdgeClose(
		p.EdgeMain,
	)
}

func _EdgeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed edge_bpfel.o
var _EdgeBytes []byte
