// Copyright 2025 Duc-Hung Ho.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package sentinez.core.tenant.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "sentinez/core/tenant/v1/model.proto";
import "sentinez/edge/v1/setting.proto";
import "sentinez/types/v1/known.proto";
import "sentinez/types/v1/model.proto";
import "sentinez/types/v1/options.proto";

option go_package = "github.com/sentinez/sentinez/api/gen/go/sentinez/core/tenant/v1;tenantpb";
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "Tenant Service"
    version: "1.0"
  }
  schemes: HTTP
  schemes: HTTPS
  consumes: "application/json"
  security_definitions: {
    security: {
      key: "ApiKeyAuth"
      value: {
        type: TYPE_API_KEY
        in: IN_HEADER
        name: "Authorization"
      }
    }
  }
  security: {
    security_requirement: {
      key: "ApiKeyAuth"
      value: {}
    }
  }
};
option (sentinez.types.v1.x_meta) = {
  service_name: "SENTINEZ // TENANT"
  service_kind: KIND_CORE
  service_key: "sentinez.core.tenant.v1"
};

// TenantService handles tenant resource management.
service TenantService {
  // Returns service health check status.
  rpc Status(StatusRequest) returns (StatusResponse) {
    option (google.api.http) = {get: "/tenant/status"};
    option (sentinez.types.v1.x_method) = {ignore: true};
  }

  // Lists tenant resources.
  rpc ListResource(ListResourceRequest) returns (ListResourceResponse) {
    option (google.api.http) = {get: "/tenant/resources"};

    option (sentinez.types.v1.x_method) = {
      consoles: [
        CONSOLE_PORTAL,
        CONSOLE_ADMIN
      ]
    };
  }

  // Creates a new tenant resource.
  rpc CreateResource(CreateResourceRequest) returns (CreateResourceResponse) {
    option (google.api.http) = {
      post: "/tenant/resource"
      body: "*"
    };

    option (sentinez.types.v1.x_method) = {
      consoles: [
        CONSOLE_PORTAL,
        CONSOLE_ADMIN
      ]
    };
  }

  // Updates an existing tenant resource.
  rpc UpdateResource(UpdateResourceRequest) returns (UpdateResourceResponse) {
    option (google.api.http) = {
      put: "/tenant/resource"
      body: "*"
    };

    option (sentinez.types.v1.x_method) = {
      consoles: [
        CONSOLE_PORTAL,
        CONSOLE_ADMIN
      ]
    };
  }

  // Deletes a tenant resource.
  rpc DeleteResource(DeleteResourceRequest) returns (DeleteResourceResponse) {
    option (google.api.http) = {delete: "/tenant/resource"};

    option (sentinez.types.v1.x_method) = {
      consoles: [
        CONSOLE_PORTAL,
        CONSOLE_ADMIN
      ]
    };
  }

  rpc GetResource(GetResourceRequest) returns (GetResourceResponse) {
    option (google.api.http) = {get: "/tenant/resource"};

    option (sentinez.types.v1.x_method) = {
      consoles: [
        CONSOLE_PORTAL,
        CONSOLE_ADMIN
      ]
    };
  }

  rpc GetResourceByDomain(GetResourceByDomainRequest) returns (GetResourceByDomainResponse) {
    option (google.api.http) = {get: "/tenant/resource/{resource_domain}"};

    option (sentinez.types.v1.x_method) = {
      consoles: [
        CONSOLE_PORTAL,
        CONSOLE_ADMIN
      ]
    };
  }
}

message GetResourceRequest {
  string id = 1 [(buf.validate.field) = {
    required: false
    string: {prefix: "senz.tenant.resources."}
  }];
  bool default = 2;
}

message GetResourceByDomainRequest {
  string resource_domain = 1 [(buf.validate.field).string.pattern = "^[a-zA-Z][a-zA-Z0-9._]{2,29}$"];
}

message GetResourceByDomainResponse {
  Resource resource = 1;
}

message GetResourceResponse {
  Resource resource = 1;
}

message DeleteResourceRequest {
  string id = 1 [(buf.validate.field) = {
    required: true
    string: {prefix: "senz.tenant.resources."}
  }];
}

message DeleteResourceResponse {}

message UpdateResourceRequest {
  string id = 1 [(buf.validate.field) = {
    required: true
    string: {prefix: "senz.tenant.resources."}
  }];
  string resource_domain = 2 [(buf.validate.field).string.pattern = "^[a-zA-Z][a-zA-Z0-9._]{2,29}$"];
  string resource_name = 3 [(buf.validate.field).string.pattern = "^[a-zA-Z][a-zA-Z0-9._]{2,29}$"];
  sentinez.types.v1.Status status = 4;
  sentinez.types.v1.Plan plan = 5;
}

message UpdateResourceResponse {}

message CreateResourceRequest {
  sentinez.edge.v1.Setting resource_setting = 1;
  string resource_domain = 2 [(buf.validate.field).string.pattern = "^[a-zA-Z][a-zA-Z0-9._]{2,29}$"];
  string resource_name = 3 [(buf.validate.field).string.pattern = "^[a-zA-Z][a-zA-Z0-9._]{2,29}$"];
  sentinez.types.v1.Status status = 4;
  sentinez.types.v1.Plan plan = 5;
}

message CreateResourceResponse {
  Resource resource = 1;
}

message ListResourceRequest {
  sentinez.types.v1.Pages page = 1;
  sentinez.types.v1.Status status = 2;
  sentinez.types.v1.Plan plan = 3;
  string resource_name = 4 [(buf.validate.field).string.pattern = "^[a-zA-Z][a-zA-Z0-9._]{2,29}$"];
  string resource_domain = 5 [(buf.validate.field).string.pattern = "^[a-zA-Z][a-zA-Z0-9._]{2,29}$"];
}

message ListResourceResponse {
  int64 total = 1;
  repeated sentinez.core.tenant.v1.Resource resources = 2;
}

message StatusResponse {
  string message = 1;
}

message StatusRequest {}
