// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resourcerepo

import (
	"context"

	tenantpb "github.com/sentinez/sentinez/api/gen/go/sentinez/modules/tenant/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIResource creates a new instance of MockIResource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIResource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIResource {
	mock := &MockIResource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIResource is an autogenerated mock type for the IResource type
type MockIResource struct {
	mock.Mock
}

type MockIResource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIResource) EXPECT() *MockIResource_Expecter {
	return &MockIResource_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIResource
func (_mock *MockIResource) Create(ctx context.Context, rs *tenantpb.Resource) (*tenantpb.Resource, error) {
	ret := _mock.Called(ctx, rs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *tenantpb.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tenantpb.Resource) (*tenantpb.Resource, error)); ok {
		return returnFunc(ctx, rs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tenantpb.Resource) *tenantpb.Resource); ok {
		r0 = returnFunc(ctx, rs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tenantpb.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *tenantpb.Resource) error); ok {
		r1 = returnFunc(ctx, rs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIResource_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIResource_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rs *tenantpb.Resource
func (_e *MockIResource_Expecter) Create(ctx interface{}, rs interface{}) *MockIResource_Create_Call {
	return &MockIResource_Create_Call{Call: _e.mock.On("Create", ctx, rs)}
}

func (_c *MockIResource_Create_Call) Run(run func(ctx context.Context, rs *tenantpb.Resource)) *MockIResource_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *tenantpb.Resource
		if args[1] != nil {
			arg1 = args[1].(*tenantpb.Resource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIResource_Create_Call) Return(resource *tenantpb.Resource, err error) *MockIResource_Create_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *MockIResource_Create_Call) RunAndReturn(run func(ctx context.Context, rs *tenantpb.Resource) (*tenantpb.Resource, error)) *MockIResource_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIResource
func (_mock *MockIResource) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIResource_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIResource_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIResource_Expecter) Delete(ctx interface{}, id interface{}) *MockIResource_Delete_Call {
	return &MockIResource_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIResource_Delete_Call) Run(run func(ctx context.Context, id string)) *MockIResource_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIResource_Delete_Call) Return(err error) *MockIResource_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIResource_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIResource_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockIResource
func (_mock *MockIResource) Get(ctx context.Context, id string) (*tenantpb.Resource, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *tenantpb.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*tenantpb.Resource, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *tenantpb.Resource); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tenantpb.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIResource_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIResource_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIResource_Expecter) Get(ctx interface{}, id interface{}) *MockIResource_Get_Call {
	return &MockIResource_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockIResource_Get_Call) Run(run func(ctx context.Context, id string)) *MockIResource_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIResource_Get_Call) Return(resource *tenantpb.Resource, err error) *MockIResource_Get_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *MockIResource_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (*tenantpb.Resource, error)) *MockIResource_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockIResource
func (_mock *MockIResource) List(ctx context.Context, req *tenantpb.ListResourceRequest) (*tenantpb.ListResourceResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *tenantpb.ListResourceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tenantpb.ListResourceRequest) (*tenantpb.ListResourceResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tenantpb.ListResourceRequest) *tenantpb.ListResourceResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tenantpb.ListResourceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *tenantpb.ListResourceRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIResource_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIResource_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *tenantpb.ListResourceRequest
func (_e *MockIResource_Expecter) List(ctx interface{}, req interface{}) *MockIResource_List_Call {
	return &MockIResource_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockIResource_List_Call) Run(run func(ctx context.Context, req *tenantpb.ListResourceRequest)) *MockIResource_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *tenantpb.ListResourceRequest
		if args[1] != nil {
			arg1 = args[1].(*tenantpb.ListResourceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIResource_List_Call) Return(listResourceResponse *tenantpb.ListResourceResponse, err error) *MockIResource_List_Call {
	_c.Call.Return(listResourceResponse, err)
	return _c
}

func (_c *MockIResource_List_Call) RunAndReturn(run func(ctx context.Context, req *tenantpb.ListResourceRequest) (*tenantpb.ListResourceResponse, error)) *MockIResource_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIResource
func (_mock *MockIResource) Update(ctx context.Context, rs *tenantpb.Resource) error {
	ret := _mock.Called(ctx, rs)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tenantpb.Resource) error); ok {
		r0 = returnFunc(ctx, rs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIResource_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIResource_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - rs *tenantpb.Resource
func (_e *MockIResource_Expecter) Update(ctx interface{}, rs interface{}) *MockIResource_Update_Call {
	return &MockIResource_Update_Call{Call: _e.mock.On("Update", ctx, rs)}
}

func (_c *MockIResource_Update_Call) Run(run func(ctx context.Context, rs *tenantpb.Resource)) *MockIResource_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *tenantpb.Resource
		if args[1] != nil {
			arg1 = args[1].(*tenantpb.Resource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIResource_Update_Call) Return(err error) *MockIResource_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIResource_Update_Call) RunAndReturn(run func(ctx context.Context, rs *tenantpb.Resource) error) *MockIResource_Update_Call {
	_c.Call.Return(run)
	return _c
}
