// Code generated by protoc-gen-go-senz. DO NOT EDIT.
// Copyright 2025 Duc-Hung Ho

package edgepb

import (
	"fmt"

	typepb "github.com/sentinez/sentinez/api/proto/sentinez/types/v1"
	"google.golang.org/protobuf/proto"
)

var (
	_ typepb.Empty
	_ fmt.Stringer
	_ proto.Message
)

var metadata_edge = &typepb.XMeta{
	ServiceName: "SENTINEZ // EDGE",
	ServiceZone: typepb.Zone_ZONE_DEMILITARIZED,
	ServiceKey:  "sentinez.dmz.edge.v1",
}

func GetMetaEdge() *typepb.XMeta {
	return proto.Clone(metadata_edge).(*typepb.XMeta)
}

func GetMetaEdgeServiceName() string {
	return metadata_edge.GetServiceName()
}

func GetMetaEdgeServiceZone() typepb.Zone {
	return metadata_edge.GetServiceZone()
}

func GetMetaEdgeServiceKey() string {
	return metadata_edge.GetServiceKey()
}
