// Copyright 2025 Duc-Hung Ho.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package sentinez.dmz.edge.v1;

import "sentinez/secure/rule/v1/engine.proto";
import "sentinez/cdn/rule/v1/cdn.proto";

import "buf/validate/validate.proto";

option go_package = "github.com/sentinez/sentinez/api/gen/go/sentinez/dmz/edge/v1;edgepb";

// Setting edge setting per user
message Setting {
  Metadata metadata = 1;      // @gotags: yaml:"metadata"
  Server server = 2;          // @gotags: yaml:"server"
  Security security = 3;      // @gotags: yaml:"security"
  Controller controller = 4;  // @gotags: yaml:"controller"
  Personal personal = 5;      // @gotags: yaml:"personal"
}

// Metadata used for observability and debugging:
message Metadata {}

// Server defines where the request goes and how the edge processes it:
message Server {
  string name = 1 [
    (buf.validate.field) = { string: { pattern: "^[a-zA-Z0-9-]+" } }
  ];  // @gotags: yaml:"name"

  repeated Location locations = 2;  // @gotags: yaml:"locations"
}

message Location {
  string location = 1 [
    (buf.validate.field) = { string: { pattern: "^/.*$" } }
  ];  // @gotags: yaml:"location"

  string proxy_rewrite = 2 [
    (buf.validate.field) = { string: { pattern: "^/.*$" } }
  ];  // @gotags: yaml:"proxyRewrite"

  repeated Upstream proxy_pass = 3;           // @gotags: yaml:"proxyPass"
  BalanceStrategy balance_strategy = 4;       // @gotags: yaml:"balanceStrategy"
  map<string, string> proxy_set_headers = 5;  // @gotags: yaml:"proxySetHeaders"
}

// Security user-specific WAF, rate limiting, or bot protection rules
message Security {
  repeated Rulesets rulesets = 1;   // @gotags: yaml:"rulesets"
  repeated RuleBased rules = 2;     // @gotags: yaml:"rules"
  repeated RateLimit limiters = 3;  // @gotags: yaml:"limiters"
}

message Rulesets {
  bool enable = 1;
}

message RuleBased {
  bool enable = 1;
  sentinez.secure.rule.v1.RuleBasedLite ingress = 2;  // @gotags: yaml:"ingress"
  sentinez.secure.rule.v1.RuleBased ingress_compiled = 3;  // @gotags: yaml:"-"
}

message RateLimit {
  bool enable = 10;  //@gotags: yaml:"isRateLimitOn"

  string time_window = 11 [(buf.validate.field) = {
    required: false
    string: { pattern: "^-?(?:\\d+(?:\\.\\d+)?(?:ns|us|µs|ms|s|m|h))+$" }
  }];  //@gotags: yaml:"timeWindow"

  int64 limit = 12;  //@gotags: yaml:"limit"

  string timeout = 13 [(buf.validate.field) = {
    required: false
    string: { pattern: "^-?(?:\\d+(?:\\.\\d+)?(?:ns|us|µs|ms|s|m|h))+$" }
  }];  //@gotags: yaml:"timeout"
}

// Controller for systems using a virtual waiting room or throttling:
message Controller {
  repeated sentinez.cdn.rule.v1.CDN cdn = 1;  // @gotags: yaml:"CDN"
}

// Personal defines where the request goes and how the edge processes it
message Personal {}

message Upstream {
  string server = 1 [(buf.validate.field) = {
    string: {
      pattern: "^(((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3})|(([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}))$"
    }
  }];  // @gotags: yaml:"server"

  ProxyProtocol protocol = 2;  // @gotags: yaml:"protocol"
}

enum BalanceStrategy {
  BALANCE_STRATEGY_UNSPECIFIED = 0;
  BALANCE_STRATEGY_ROUND_ROBIN = 1;
}

enum ProxyProtocol {
  PROXY_PROTOCOL_UNSPECIFIED = 0;
  PROXY_PROTOCOL_HTTP = 1;
  PROXY_PROTOCOL_HTTPS = 2;
}
