#!/usr/bin/env bash
set -e

REPO_URL="https://github.com/sentinez/shared.git"

PREFIX="staging/src/github.com/sentinez/shared"

BRANCH="main"

echo "Fetching updates..."
git fetch origin

echo "Pushing subtree '$PREFIX' to repo..."
git subtree push --prefix="$PREFIX" "$REPO_URL" "$BRANCH"

echo "Done!"
