#!/usr/bin/env bash
set -e

# Check arguments
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Error: Missing arguments."
    echo "Usage: ./push_subtree.sh <module-name> <remote-url>"
    exit 1
fi

NAME="$1"
REMOTE="$2"

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
PREFIX="staging/src/github.com/sentinez/${NAME}"
BRANCH="$CURRENT_BRANCH"

echo "MODULE:   $NAME"
echo "REMOTE:   $REMOTE"
echo "PREFIX:   $PREFIX"
echo "BRANCH:   $BRANCH"
echo

echo "Fetching updates..."
git fetch origin

echo "Pushing subtree '$PREFIX' to remote '$REMOTE' on branch '$BRANCH'..."
git subtree push --prefix="$PREFIX" "$REMOTE" "$BRANCH"

echo "Done."
