// Code generated by ruleparser-sentinez. DO NOT EDIT.
// Copyright 2025 Duc-Hung Ho
package rules

import (
	"github.com/sentinez/sentinez/api/gen/go/sentinez/edge/waf/v1"
)

const DefaultVersion = ""

var DefaultOrder = []func() *waf.Rule{
	Default_auto_0,
	R1,
	Default_auto_2,
	R100,
	R933150,
}

var Default = map[string]*waf.Rule{
	"Default_auto_0": Default_auto_0(),

	"1": R1(),

	"Default_auto_2": Default_auto_2(),

	"100": R100(),

	"933150": R933150(),
}

// Default_auto_0 returns rule without ID
func Default_auto_0() *waf.Rule {
	return &waf.Rule{
		Actions: &waf.RuleAction{
			Statement: "U2VjRGVidWdMb2cgL2Rldi9zdGRvdXQ=",
			Fields:    &waf.RuleActionField{},
		},
		Configuration: "U2VjRGVidWdMb2cgL2Rldi9zdGRvdXQ=",
		Level:         "",
	}
}

// R1 returns rule with ID 1
func R1() *waf.Rule {
	return &waf.Rule{
		Actions: &waf.RuleAction{
			Statement: "U2VjUnVsZSBBUkdTOmlkICJAZXEgMCIgImlkOjEsIHBoYXNlOjEsZGVueSwgc3RhdHVzOjQwMyxtc2c6J0ludmFsaWQgaWQnLGxvZyxhdWRpdGxvZyI=",
			Fields:    &waf.RuleActionField{Id: []string{"1"}, Msg: []string{"'Invalid id'"}, Phase: []string{"1"}},
		},
		Configuration: "U2VjUnVsZSBBUkdTOmlkICJAZXEgMCIgImlkOjEsIHBoYXNlOjEsZGVueSwgc3RhdHVzOjQwMyxtc2c6J0ludmFsaWQgaWQnLGxvZyxhdWRpdGxvZyI=",
		Level:         "",
	}
}

// Default_auto_2 returns rule without ID
func Default_auto_2() *waf.Rule {
	return &waf.Rule{
		Actions: &waf.RuleAction{
			Statement: "U2VjUmVxdWVzdEJvZHlBY2Nlc3MgT24=",
			Fields:    &waf.RuleActionField{},
		},
		Configuration: "U2VjUmVxdWVzdEJvZHlBY2Nlc3MgT24=",
		Level:         "",
	}
}

// R100 returns rule with ID 100
func R100() *waf.Rule {
	return &waf.Rule{
		Actions: &waf.RuleAction{
			Statement: "U2VjUnVsZSBSRVFVRVNUX0JPRFkgIkBjb250YWlucyBwYXNzd29yZCIgImlkOjEwMCwgcGhhc2U6MixkZW55LCBzdGF0dXM6NDAzLG1zZzonSW52YWxpZCByZXF1ZXN0IGJvZHknLGxvZyxhdWRpdGxvZyI=",
			Fields:    &waf.RuleActionField{Id: []string{"100"}, Msg: []string{"'Invalid request body'"}, Phase: []string{"2"}},
		},
		Configuration: "U2VjUnVsZSBSRVFVRVNUX0JPRFkgIkBjb250YWlucyBwYXNzd29yZCIgImlkOjEwMCwgcGhhc2U6MixkZW55LCBzdGF0dXM6NDAzLG1zZzonSW52YWxpZCByZXF1ZXN0IGJvZHknLGxvZyxhdWRpdGxvZyI=",
		Level:         "",
	}
}

// R933150 returns rule with ID 933150
func R933150() *waf.Rule {
	return &waf.Rule{
		Actions: &waf.RuleAction{
			Statement: "U2VjUnVsZSBBUkdTICJAcG1Gcm9tRmlsZSBwaHAtZnVuY3Rpb24tbmFtZXMtOTMzMTUwLmRhdGEiIFwKICAgICJpZDo5MzMxNTAscGhhc2U6MixibG9jayxtc2c6J1BIUCBmdW5jdGlvbiBpbmplY3Rpb24gZGV0ZWN0ZWQnIg==",
			Fields:    &waf.RuleActionField{Id: []string{"933150"}, Msg: []string{"'PHP function injection detected'"}, Phase: []string{"2"}},
		},
		Configuration: "U2VjUnVsZSBBUkdTICJAcG1Gcm9tRmlsZSBwaHAtZnVuY3Rpb24tbmFtZXMtOTMzMTUwLmRhdGEiIFwKICAgICJpZDo5MzMxNTAscGhhc2U6MixibG9jayxtc2c6J1BIUCBmdW5jdGlvbiBpbmplY3Rpb24gZGV0ZWN0ZWQnIg==",
		Level:         "",
	}
}
