// Copyright 2026 Duc-Hung Ho.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sentinez/secure/rule/v1/engine.proto

package rulepb

import (
	v1 "github.com/sentinez/sentinez/api/proto/sentinez/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The possible sources from which a field can be extracted in a request
type FieldSource int32

const (
	FieldSource_FIELD_SOURCE_UNSPECIFIED FieldSource = 0
	FieldSource_FIELD_SOURCE_HEADER      FieldSource = 1
	FieldSource_FIELD_SOURCE_QUERY       FieldSource = 2
	FieldSource_FIELD_SOURCE_PATH        FieldSource = 3
	FieldSource_FIELD_SOURCE_BODY        FieldSource = 4
	FieldSource_FIELD_SOURCE_IP          FieldSource = 5
	FieldSource_FIELD_SOURCE_JA4         FieldSource = 6
	FieldSource_FIELD_SOURCE_TLS         FieldSource = 7
	FieldSource_FIELD_SOURCE_METHOD      FieldSource = 8
	FieldSource_FIELD_SOURCE_HOST        FieldSource = 9
)

// Enum value maps for FieldSource.
var (
	FieldSource_name = map[int32]string{
		0: "FIELD_SOURCE_UNSPECIFIED",
		1: "FIELD_SOURCE_HEADER",
		2: "FIELD_SOURCE_QUERY",
		3: "FIELD_SOURCE_PATH",
		4: "FIELD_SOURCE_BODY",
		5: "FIELD_SOURCE_IP",
		6: "FIELD_SOURCE_JA4",
		7: "FIELD_SOURCE_TLS",
		8: "FIELD_SOURCE_METHOD",
		9: "FIELD_SOURCE_HOST",
	}
	FieldSource_value = map[string]int32{
		"FIELD_SOURCE_UNSPECIFIED": 0,
		"FIELD_SOURCE_HEADER":      1,
		"FIELD_SOURCE_QUERY":       2,
		"FIELD_SOURCE_PATH":        3,
		"FIELD_SOURCE_BODY":        4,
		"FIELD_SOURCE_IP":          5,
		"FIELD_SOURCE_JA4":         6,
		"FIELD_SOURCE_TLS":         7,
		"FIELD_SOURCE_METHOD":      8,
		"FIELD_SOURCE_HOST":        9,
	}
)

func (x FieldSource) Enum() *FieldSource {
	p := new(FieldSource)
	*p = x
	return p
}

func (x FieldSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldSource) Descriptor() protoreflect.EnumDescriptor {
	return file_sentinez_secure_rule_v1_engine_proto_enumTypes[0].Descriptor()
}

func (FieldSource) Type() protoreflect.EnumType {
	return &file_sentinez_secure_rule_v1_engine_proto_enumTypes[0]
}

func (x FieldSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldSource.Descriptor instead.
func (FieldSource) EnumDescriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{0}
}

type Operator int32

const (
	Operator_OPERATOR_UNSPECIFIED Operator = 0
	Operator_OPERATOR_EQ          Operator = 1
	Operator_OPERATOR_NE          Operator = 2
	Operator_OPERATOR_CONTAINS    Operator = 3
	Operator_OPERATOR_MATCHES     Operator = 4
	Operator_OPERATOR_IN          Operator = 5
	Operator_OPERATOR_PREFIX      Operator = 6
	Operator_OPERATOR_SUFFIX      Operator = 7
	Operator_OPERATOR_GT          Operator = 8
	Operator_OPERATOR_GTE         Operator = 9
	Operator_OPERATOR_LT          Operator = 10
	Operator_OPERATOR_LTE         Operator = 11
	Operator_OPERATOR_NOT_IN      Operator = 12
)

// Enum value maps for Operator.
var (
	Operator_name = map[int32]string{
		0:  "OPERATOR_UNSPECIFIED",
		1:  "OPERATOR_EQ",
		2:  "OPERATOR_NE",
		3:  "OPERATOR_CONTAINS",
		4:  "OPERATOR_MATCHES",
		5:  "OPERATOR_IN",
		6:  "OPERATOR_PREFIX",
		7:  "OPERATOR_SUFFIX",
		8:  "OPERATOR_GT",
		9:  "OPERATOR_GTE",
		10: "OPERATOR_LT",
		11: "OPERATOR_LTE",
		12: "OPERATOR_NOT_IN",
	}
	Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED": 0,
		"OPERATOR_EQ":          1,
		"OPERATOR_NE":          2,
		"OPERATOR_CONTAINS":    3,
		"OPERATOR_MATCHES":     4,
		"OPERATOR_IN":          5,
		"OPERATOR_PREFIX":      6,
		"OPERATOR_SUFFIX":      7,
		"OPERATOR_GT":          8,
		"OPERATOR_GTE":         9,
		"OPERATOR_LT":          10,
		"OPERATOR_LTE":         11,
		"OPERATOR_NOT_IN":      12,
	}
)

func (x Operator) Enum() *Operator {
	p := new(Operator)
	*p = x
	return p
}

func (x Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_sentinez_secure_rule_v1_engine_proto_enumTypes[1].Descriptor()
}

func (Operator) Type() protoreflect.EnumType {
	return &file_sentinez_secure_rule_v1_engine_proto_enumTypes[1]
}

func (x Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operator.Descriptor instead.
func (Operator) EnumDescriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{1}
}

type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED   ActionType = 0
	ActionType_ACTION_TYPE_BLOCK         ActionType = 1
	ActionType_ACTION_TYPE_LOG           ActionType = 2
	ActionType_ACTION_TYPE_MODIFY_HEADER ActionType = 3
	ActionType_ACTION_TYPE_REDIRECT      ActionType = 4
	ActionType_ACTION_TYPE_SET_TAG       ActionType = 5
	ActionType_ACTION_TYPE_ROUTE_TO      ActionType = 6
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_BLOCK",
		2: "ACTION_TYPE_LOG",
		3: "ACTION_TYPE_MODIFY_HEADER",
		4: "ACTION_TYPE_REDIRECT",
		5: "ACTION_TYPE_SET_TAG",
		6: "ACTION_TYPE_ROUTE_TO",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED":   0,
		"ACTION_TYPE_BLOCK":         1,
		"ACTION_TYPE_LOG":           2,
		"ACTION_TYPE_MODIFY_HEADER": 3,
		"ACTION_TYPE_REDIRECT":      4,
		"ACTION_TYPE_SET_TAG":       5,
		"ACTION_TYPE_ROUTE_TO":      6,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_sentinez_secure_rule_v1_engine_proto_enumTypes[2].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_sentinez_secure_rule_v1_engine_proto_enumTypes[2]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{2}
}

// A logical condition expression
type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty" yaml:"-"` // @gotags: yaml:"-"
	// The source of the field
	// Example: "User-Agent" or "country"
	Source FieldSource `protobuf:"varint,1,opt,name=source,proto3,enum=sentinez.secure.rule.v1.FieldSource" json:"source,omitempty" yaml:"source"` // @gotags: yaml:"source"
	Key    string      `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty" yaml:"key"`                                                 // @gotags: yaml:"key"
	// Supported operators: "eq", "ne", "contains",
	// "matches", "in", "prefix", "suffix", "gt", "lt"
	Operator Operator `protobuf:"varint,3,opt,name=operator,proto3,enum=sentinez.secure.rule.v1.Operator" json:"operator,omitempty" yaml:"operator"` // @gotags: yaml:"operator"
	// The value to compare against
	Value         *structpb.Value `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty" yaml:"value"` // @gotags: yaml:"value"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{0}
}

func (x *Condition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Condition) GetSource() FieldSource {
	if x != nil {
		return x.Source
	}
	return FieldSource_FIELD_SOURCE_UNSPECIFIED
}

func (x *Condition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Condition) GetOperator() Operator {
	if x != nil {
		return x.Operator
	}
	return Operator_OPERATOR_UNSPECIFIED
}

func (x *Condition) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// An action to execute when a rule matches
type Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Example types: "block", "log", "modify_header",
	// "redirect", "set_tag", "route_to"
	Type ActionType `protobuf:"varint,1,opt,name=type,proto3,enum=sentinez.secure.rule.v1.ActionType" json:"type,omitempty" yaml:"type"` // @gotags: yaml:"type"
	// Dynamic parameters, e.g., { "status": 403, "message": "Forbidden" }
	Params        *structpb.Struct `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty" yaml:"params"` // @gotags: yaml:"params"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *Action) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

// A complete rule definition
type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" yaml:"name"` // @gotags: yaml:"name"
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Condition     *Condition             `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty" yaml:"condition"` // @gotags: yaml:"condition"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{2}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rule) GetCondition() *Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

type AndCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	OrCondition   []*AndCondition        `protobuf:"bytes,2,rep,name=or_condition,json=orCondition,proto3" json:"or_condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AndCondition) Reset() {
	*x = AndCondition{}
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AndCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndCondition) ProtoMessage() {}

func (x *AndCondition) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndCondition.ProtoReflect.Descriptor instead.
func (*AndCondition) Descriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{3}
}

func (x *AndCondition) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *AndCondition) GetOrCondition() []*AndCondition {
	if x != nil {
		return x.OrCondition
	}
	return nil
}

type AndConditionLite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*RuleLite            `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	OrCondition   []*AndConditionLite    `protobuf:"bytes,2,rep,name=or_condition,json=orCondition,proto3" json:"or_condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AndConditionLite) Reset() {
	*x = AndConditionLite{}
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AndConditionLite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndConditionLite) ProtoMessage() {}

func (x *AndConditionLite) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndConditionLite.ProtoReflect.Descriptor instead.
func (*AndConditionLite) Descriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{4}
}

func (x *AndConditionLite) GetRules() []*RuleLite {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *AndConditionLite) GetOrCondition() []*AndConditionLite {
	if x != nil {
		return x.OrCondition
	}
	return nil
}

// A complete rule definition
type RuleLite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" yaml:"name"`           // @gotags: yaml:"name"
	Condition     *ConditionLite         `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty" yaml:"condition"` // @gotags: yaml:"condition"
	Actions       []string               `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty" yaml:"actions"`     // @gotags: yaml:"actions"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleLite) Reset() {
	*x = RuleLite{}
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleLite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleLite) ProtoMessage() {}

func (x *RuleLite) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleLite.ProtoReflect.Descriptor instead.
func (*RuleLite) Descriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{5}
}

func (x *RuleLite) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuleLite) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleLite) GetCondition() *ConditionLite {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *RuleLite) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

// A logical condition expression
type ConditionLite struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source of the field
	// Example: "User-Agent" or "country"
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty" yaml:"source"` // @gotags: yaml:"source"
	Key    string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty" yaml:"key"`       // @gotags: yaml:"key"
	// Supported operators: "eq", "ne", "contains",
	// "matches", "in", "prefix", "suffix", "gt", "lt"
	Operator string `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty" yaml:"operator"` // @gotags: yaml:"operator"
	// The value to compare against
	Value         string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty" yaml:"value"` // @gotags: yaml:"value"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionLite) Reset() {
	*x = ConditionLite{}
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionLite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionLite) ProtoMessage() {}

func (x *ConditionLite) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionLite.ProtoReflect.Descriptor instead.
func (*ConditionLite) Descriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{6}
}

func (x *ConditionLite) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ConditionLite) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConditionLite) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ConditionLite) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Expression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrCondition   []*AndCondition        `protobuf:"bytes,1,rep,name=or_condition,json=orCondition,proto3" json:"or_condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expression) Reset() {
	*x = Expression{}
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{7}
}

func (x *Expression) GetOrCondition() []*AndCondition {
	if x != nil {
		return x.OrCondition
	}
	return nil
}

type ExpressionLite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrCondition   []*AndConditionLite    `protobuf:"bytes,1,rep,name=or_condition,json=orCondition,proto3" json:"or_condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionLite) Reset() {
	*x = ExpressionLite{}
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionLite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionLite) ProtoMessage() {}

func (x *ExpressionLite) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionLite.ProtoReflect.Descriptor instead.
func (*ExpressionLite) Descriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{8}
}

func (x *ExpressionLite) GetOrCondition() []*AndConditionLite {
	if x != nil {
		return x.OrCondition
	}
	return nil
}

type MatchedRules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchedRules) Reset() {
	*x = MatchedRules{}
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchedRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchedRules) ProtoMessage() {}

func (x *MatchedRules) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchedRules.ProtoReflect.Descriptor instead.
func (*MatchedRules) Descriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{9}
}

func (x *MatchedRules) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *MatchedRules) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type RuleBased struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Expr          *Expression            `protobuf:"bytes,4,opt,name=expr,proto3" json:"expr,omitempty"`
	Action        *Action                `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Status        v1.Status              `protobuf:"varint,6,opt,name=status,proto3,enum=sentinez.types.v1.Status" json:"status,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleBased) Reset() {
	*x = RuleBased{}
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleBased) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleBased) ProtoMessage() {}

func (x *RuleBased) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleBased.ProtoReflect.Descriptor instead.
func (*RuleBased) Descriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{10}
}

func (x *RuleBased) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuleBased) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleBased) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleBased) GetExpr() *Expression {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *RuleBased) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *RuleBased) GetStatus() v1.Status {
	if x != nil {
		return x.Status
	}
	return v1.Status(0)
}

func (x *RuleBased) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RuleBased) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RuleBased) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RuleBasedLite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Expr          *ExpressionLite        `protobuf:"bytes,4,opt,name=expr,proto3" json:"expr,omitempty"`
	Action        *Action                `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleBasedLite) Reset() {
	*x = RuleBasedLite{}
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleBasedLite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleBasedLite) ProtoMessage() {}

func (x *RuleBasedLite) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_secure_rule_v1_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleBasedLite.ProtoReflect.Descriptor instead.
func (*RuleBasedLite) Descriptor() ([]byte, []int) {
	return file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP(), []int{11}
}

func (x *RuleBasedLite) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuleBasedLite) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleBasedLite) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleBasedLite) GetExpr() *ExpressionLite {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *RuleBasedLite) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

var File_sentinez_secure_rule_v1_engine_proto protoreflect.FileDescriptor

const file_sentinez_secure_rule_v1_engine_proto_rawDesc = "" +
	"\n" +
	"$sentinez/secure/rule/v1/engine.proto\x12\x17sentinez.secure.rule.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dsentinez/types/v1/known.proto\"\xd8\x01\n" +
	"\tCondition\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12<\n" +
	"\x06source\x18\x01 \x01(\x0e2$.sentinez.secure.rule.v1.FieldSourceR\x06source\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12=\n" +
	"\boperator\x18\x03 \x01(\x0e2!.sentinez.secure.rule.v1.OperatorR\boperator\x12,\n" +
	"\x05value\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\x05value\"r\n" +
	"\x06Action\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.sentinez.secure.rule.v1.ActionTypeR\x04type\x12/\n" +
	"\x06params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06params\"\x8e\x01\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12@\n" +
	"\tcondition\x18\x04 \x01(\v2\".sentinez.secure.rule.v1.ConditionR\tcondition\"\x8d\x01\n" +
	"\fAndCondition\x123\n" +
	"\x05rules\x18\x01 \x03(\v2\x1d.sentinez.secure.rule.v1.RuleR\x05rules\x12H\n" +
	"\for_condition\x18\x02 \x03(\v2%.sentinez.secure.rule.v1.AndConditionR\vorCondition\"\x99\x01\n" +
	"\x10AndConditionLite\x127\n" +
	"\x05rules\x18\x01 \x03(\v2!.sentinez.secure.rule.v1.RuleLiteR\x05rules\x12L\n" +
	"\for_condition\x18\x02 \x03(\v2).sentinez.secure.rule.v1.AndConditionLiteR\vorCondition\"\x8e\x01\n" +
	"\bRuleLite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12D\n" +
	"\tcondition\x18\x04 \x01(\v2&.sentinez.secure.rule.v1.ConditionLiteR\tcondition\x12\x18\n" +
	"\aactions\x18\x05 \x03(\tR\aactions\"k\n" +
	"\rConditionLite\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"V\n" +
	"\n" +
	"Expression\x12H\n" +
	"\for_condition\x18\x01 \x03(\v2%.sentinez.secure.rule.v1.AndConditionR\vorCondition\"^\n" +
	"\x0eExpressionLite\x12L\n" +
	"\for_condition\x18\x01 \x03(\v2).sentinez.secure.rule.v1.AndConditionLiteR\vorCondition\"6\n" +
	"\fMatchedRules\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\"\x88\x03\n" +
	"\tRuleBased\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\x04expr\x18\x04 \x01(\v2#.sentinez.secure.rule.v1.ExpressionR\x04expr\x127\n" +
	"\x06action\x18\x05 \x01(\v2\x1f.sentinez.secure.rule.v1.ActionR\x06action\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.sentinez.types.v1.StatusR\x06status\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xcb\x01\n" +
	"\rRuleBasedLite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12;\n" +
	"\x04expr\x18\x04 \x01(\v2'.sentinez.secure.rule.v1.ExpressionLiteR\x04expr\x127\n" +
	"\x06action\x18\x05 \x01(\v2\x1f.sentinez.secure.rule.v1.ActionR\x06action*\xfb\x01\n" +
	"\vFieldSource\x12\x1c\n" +
	"\x18FIELD_SOURCE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FIELD_SOURCE_HEADER\x10\x01\x12\x16\n" +
	"\x12FIELD_SOURCE_QUERY\x10\x02\x12\x15\n" +
	"\x11FIELD_SOURCE_PATH\x10\x03\x12\x15\n" +
	"\x11FIELD_SOURCE_BODY\x10\x04\x12\x13\n" +
	"\x0fFIELD_SOURCE_IP\x10\x05\x12\x14\n" +
	"\x10FIELD_SOURCE_JA4\x10\x06\x12\x14\n" +
	"\x10FIELD_SOURCE_TLS\x10\a\x12\x17\n" +
	"\x13FIELD_SOURCE_METHOD\x10\b\x12\x15\n" +
	"\x11FIELD_SOURCE_HOST\x10\t*\x89\x02\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOPERATOR_EQ\x10\x01\x12\x0f\n" +
	"\vOPERATOR_NE\x10\x02\x12\x15\n" +
	"\x11OPERATOR_CONTAINS\x10\x03\x12\x14\n" +
	"\x10OPERATOR_MATCHES\x10\x04\x12\x0f\n" +
	"\vOPERATOR_IN\x10\x05\x12\x13\n" +
	"\x0fOPERATOR_PREFIX\x10\x06\x12\x13\n" +
	"\x0fOPERATOR_SUFFIX\x10\a\x12\x0f\n" +
	"\vOPERATOR_GT\x10\b\x12\x10\n" +
	"\fOPERATOR_GTE\x10\t\x12\x0f\n" +
	"\vOPERATOR_LT\x10\n" +
	"\x12\x10\n" +
	"\fOPERATOR_LTE\x10\v\x12\x13\n" +
	"\x0fOPERATOR_NOT_IN\x10\f*\xc1\x01\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTION_TYPE_BLOCK\x10\x01\x12\x13\n" +
	"\x0fACTION_TYPE_LOG\x10\x02\x12\x1d\n" +
	"\x19ACTION_TYPE_MODIFY_HEADER\x10\x03\x12\x18\n" +
	"\x14ACTION_TYPE_REDIRECT\x10\x04\x12\x17\n" +
	"\x13ACTION_TYPE_SET_TAG\x10\x05\x12\x18\n" +
	"\x14ACTION_TYPE_ROUTE_TO\x10\x06BGZEgithub.com/sentinez/sentinez/api/proto/sentinez/secure/rule/v1;rulepbb\x06proto3"

var (
	file_sentinez_secure_rule_v1_engine_proto_rawDescOnce sync.Once
	file_sentinez_secure_rule_v1_engine_proto_rawDescData []byte
)

func file_sentinez_secure_rule_v1_engine_proto_rawDescGZIP() []byte {
	file_sentinez_secure_rule_v1_engine_proto_rawDescOnce.Do(func() {
		file_sentinez_secure_rule_v1_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinez_secure_rule_v1_engine_proto_rawDesc), len(file_sentinez_secure_rule_v1_engine_proto_rawDesc)))
	})
	return file_sentinez_secure_rule_v1_engine_proto_rawDescData
}

var file_sentinez_secure_rule_v1_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sentinez_secure_rule_v1_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sentinez_secure_rule_v1_engine_proto_goTypes = []any{
	(FieldSource)(0),              // 0: sentinez.secure.rule.v1.FieldSource
	(Operator)(0),                 // 1: sentinez.secure.rule.v1.Operator
	(ActionType)(0),               // 2: sentinez.secure.rule.v1.ActionType
	(*Condition)(nil),             // 3: sentinez.secure.rule.v1.Condition
	(*Action)(nil),                // 4: sentinez.secure.rule.v1.Action
	(*Rule)(nil),                  // 5: sentinez.secure.rule.v1.Rule
	(*AndCondition)(nil),          // 6: sentinez.secure.rule.v1.AndCondition
	(*AndConditionLite)(nil),      // 7: sentinez.secure.rule.v1.AndConditionLite
	(*RuleLite)(nil),              // 8: sentinez.secure.rule.v1.RuleLite
	(*ConditionLite)(nil),         // 9: sentinez.secure.rule.v1.ConditionLite
	(*Expression)(nil),            // 10: sentinez.secure.rule.v1.Expression
	(*ExpressionLite)(nil),        // 11: sentinez.secure.rule.v1.ExpressionLite
	(*MatchedRules)(nil),          // 12: sentinez.secure.rule.v1.MatchedRules
	(*RuleBased)(nil),             // 13: sentinez.secure.rule.v1.RuleBased
	(*RuleBasedLite)(nil),         // 14: sentinez.secure.rule.v1.RuleBasedLite
	(*structpb.Value)(nil),        // 15: google.protobuf.Value
	(*structpb.Struct)(nil),       // 16: google.protobuf.Struct
	(v1.Status)(0),                // 17: sentinez.types.v1.Status
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_sentinez_secure_rule_v1_engine_proto_depIdxs = []int32{
	0,  // 0: sentinez.secure.rule.v1.Condition.source:type_name -> sentinez.secure.rule.v1.FieldSource
	1,  // 1: sentinez.secure.rule.v1.Condition.operator:type_name -> sentinez.secure.rule.v1.Operator
	15, // 2: sentinez.secure.rule.v1.Condition.value:type_name -> google.protobuf.Value
	2,  // 3: sentinez.secure.rule.v1.Action.type:type_name -> sentinez.secure.rule.v1.ActionType
	16, // 4: sentinez.secure.rule.v1.Action.params:type_name -> google.protobuf.Struct
	3,  // 5: sentinez.secure.rule.v1.Rule.condition:type_name -> sentinez.secure.rule.v1.Condition
	5,  // 6: sentinez.secure.rule.v1.AndCondition.rules:type_name -> sentinez.secure.rule.v1.Rule
	6,  // 7: sentinez.secure.rule.v1.AndCondition.or_condition:type_name -> sentinez.secure.rule.v1.AndCondition
	8,  // 8: sentinez.secure.rule.v1.AndConditionLite.rules:type_name -> sentinez.secure.rule.v1.RuleLite
	7,  // 9: sentinez.secure.rule.v1.AndConditionLite.or_condition:type_name -> sentinez.secure.rule.v1.AndConditionLite
	9,  // 10: sentinez.secure.rule.v1.RuleLite.condition:type_name -> sentinez.secure.rule.v1.ConditionLite
	6,  // 11: sentinez.secure.rule.v1.Expression.or_condition:type_name -> sentinez.secure.rule.v1.AndCondition
	7,  // 12: sentinez.secure.rule.v1.ExpressionLite.or_condition:type_name -> sentinez.secure.rule.v1.AndConditionLite
	10, // 13: sentinez.secure.rule.v1.RuleBased.expr:type_name -> sentinez.secure.rule.v1.Expression
	4,  // 14: sentinez.secure.rule.v1.RuleBased.action:type_name -> sentinez.secure.rule.v1.Action
	17, // 15: sentinez.secure.rule.v1.RuleBased.status:type_name -> sentinez.types.v1.Status
	18, // 16: sentinez.secure.rule.v1.RuleBased.created_at:type_name -> google.protobuf.Timestamp
	18, // 17: sentinez.secure.rule.v1.RuleBased.updated_at:type_name -> google.protobuf.Timestamp
	11, // 18: sentinez.secure.rule.v1.RuleBasedLite.expr:type_name -> sentinez.secure.rule.v1.ExpressionLite
	4,  // 19: sentinez.secure.rule.v1.RuleBasedLite.action:type_name -> sentinez.secure.rule.v1.Action
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_sentinez_secure_rule_v1_engine_proto_init() }
func file_sentinez_secure_rule_v1_engine_proto_init() {
	if File_sentinez_secure_rule_v1_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinez_secure_rule_v1_engine_proto_rawDesc), len(file_sentinez_secure_rule_v1_engine_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sentinez_secure_rule_v1_engine_proto_goTypes,
		DependencyIndexes: file_sentinez_secure_rule_v1_engine_proto_depIdxs,
		EnumInfos:         file_sentinez_secure_rule_v1_engine_proto_enumTypes,
		MessageInfos:      file_sentinez_secure_rule_v1_engine_proto_msgTypes,
	}.Build()
	File_sentinez_secure_rule_v1_engine_proto = out.File
	file_sentinez_secure_rule_v1_engine_proto_goTypes = nil
	file_sentinez_secure_rule_v1_engine_proto_depIdxs = nil
}
