syntax = "proto3";

package sentinez.secure.rule.v1;

import "sentinez/secure/rule/v1/rule.proto";
import "sentinez/types/v1/options.proto";

option go_package = "github.com/sentinez/sentinez/api/gen/go/sentinez/secure/rule/v1;rulepb";

message Event {
  option (sentinez.types.v1.x_message).database_model = true;

  repeated int32 rule_ids = 1;
  repeated string severities = 2;
  repeated string messages = 3;
  string path = 4;
  int32 score = 5;
  string ip = 6;
  string request_domain = 7;
  string transaction_id = 8;
  int64 request_time = 9; // milisec
  sentinez.secure.rule.v1.RuleService service = 10;
  sentinez.secure.rule.v1.RuleBehavior behavior = 11;
  string http_req_id = 12;
  string content_type = 13;
}
