syntax = "proto3";

package sentinez.secure.rule.v1;

option go_package = "github.com/sentinez/sentinez/api/gen/go/sentinez/secure/rule/v1;rulepb";

message CoreRulesets {
  string name = 1;
  repeated CoreRule core_rules = 2;
  string version = 3;
}

message CoreRule {
  RuleAction actions = 1;
  string configuration = 2;
  string level = 3;
}

message RuleAction {
  string statement = 1;
  RuleAction children = 2;
  RuleActionField fields = 3;
}

message RuleActionField {
  repeated string id = 1;
  repeated string logdata = 2;
  repeated string msg = 3;
  repeated string phase = 4;
  repeated string setvar = 5;
  repeated string severity = 6;
  repeated string t = 7;
  repeated string ver = 8;
  repeated string tag = 9;
}

enum RuleService {
  RULE_SERVICE_UNSPECIFIED = 0;
  RULE_SERVICE_CORE_RULESETS = 1;
  RULE_SERVICE_CUSTOM_RULES = 2;
  RULE_SERVICE_RATE_LIMIT = 3;
}

enum RuleBehavior {
  RULE_BEHAVIOR_UNSPECIFIED = 0;
  RULE_BEHAVIOR_DENY = 1;
}
