// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/sentinez/sentinez/api/gen/go/sentinez/v1"
	"github.com/sentinez/sentinez/internal/apiserver/services/v1"
	"github.com/sentinez/sentinez/internal/core/greeter/v1/domain"
	"github.com/sentinez/sentinez/internal/core/greeter/v1/handler"
	"github.com/sentinez/sentinez/internal/core/iam/v1/domain"
	"github.com/sentinez/sentinez/internal/core/iam/v1/handler"
	"github.com/sentinez/sentinez/internal/core/iam/v1/repos/users"
	"github.com/sentinez/sentinez/internal/core/tenant/v1/handler"
	"github.com/sentinez/sentinez/pkg/core/gateway/http"
	"github.com/sentinez/sentinez/pkg/infra/utils"
)

// Injectors from wire.go:

func NewDefaultGreeter() httpgw.ServiceRegistrar {
	iGreeter := greeterdomain.New()
	greeterServiceServer := greeterhandler.New(iGreeter)
	serviceRegistrar := services.NewGreeter(greeterServiceServer)
	return serviceRegistrar
}

func NewDefaultIAM(conf *sentinez.Config) (httpgw.ServiceRegistrar, error) {
	pool, err := utils.NewPgxPool(conf)
	if err != nil {
		return nil, err
	}
	iUser, err := usersrepo.New(pool)
	if err != nil {
		return nil, err
	}
	identityAccessManagerDomainServiceServer := iamdomains.New(iUser)
	identityAccessManagementServiceServer := iamhandler.New(identityAccessManagerDomainServiceServer)
	serviceRegistrar := services.NewIAM(identityAccessManagementServiceServer)
	return serviceRegistrar, nil
}

func NewDefaultTenant() httpgw.ServiceRegistrar {
	tenantServiceServer := tenanthandler.New()
	serviceRegistrar := services.NewTenant(tenantServiceServer)
	return serviceRegistrar
}
