// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usersrepo

import (
	"context"

	"github.com/sentinez/core/storage/dbx/postgres"
	usersrepo "github.com/sentinez/modules/iam/v1/repos/users"
	iampb "github.com/sentinez/sentinez/api/gen/go/sentinez/modules/iam/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIUser creates a new instance of MockIUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUser {
	mock := &MockIUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUser is an autogenerated mock type for the IUser type
type MockIUser struct {
	mock.Mock
}

type MockIUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUser) EXPECT() *MockIUser_Expecter {
	return &MockIUser_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIUser
func (_mock *MockIUser) Create(ctx context.Context, user *iampb.User) (*iampb.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *iampb.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iampb.User) (*iampb.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iampb.User) *iampb.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iampb.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *iampb.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUser_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIUser_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *iampb.User
func (_e *MockIUser_Expecter) Create(ctx interface{}, user interface{}) *MockIUser_Create_Call {
	return &MockIUser_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockIUser_Create_Call) Run(run func(ctx context.Context, user *iampb.User)) *MockIUser_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *iampb.User
		if args[1] != nil {
			arg1 = args[1].(*iampb.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUser_Create_Call) Return(user1 *iampb.User, err error) *MockIUser_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockIUser_Create_Call) RunAndReturn(run func(ctx context.Context, user *iampb.User) (*iampb.User, error)) *MockIUser_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIUser
func (_mock *MockIUser) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUser_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIUser_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIUser_Expecter) Delete(ctx interface{}, id interface{}) *MockIUser_Delete_Call {
	return &MockIUser_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIUser_Delete_Call) Run(run func(ctx context.Context, id string)) *MockIUser_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUser_Delete_Call) Return(err error) *MockIUser_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUser_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIUser_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockIUser
func (_mock *MockIUser) Get(ctx context.Context, id string) (*iampb.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *iampb.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*iampb.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *iampb.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iampb.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUser_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIUser_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIUser_Expecter) Get(ctx interface{}, id interface{}) *MockIUser_Get_Call {
	return &MockIUser_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockIUser_Get_Call) Run(run func(ctx context.Context, id string)) *MockIUser_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUser_Get_Call) Return(user *iampb.User, err error) *MockIUser_Get_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUser_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (*iampb.User, error)) *MockIUser_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByFullnameOrEmail provides a mock function for the type MockIUser
func (_mock *MockIUser) GetByFullnameOrEmail(ctx context.Context, input string) (*iampb.User, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetByFullnameOrEmail")
	}

	var r0 *iampb.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*iampb.User, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *iampb.User); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iampb.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUser_GetByFullnameOrEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByFullnameOrEmail'
type MockIUser_GetByFullnameOrEmail_Call struct {
	*mock.Call
}

// GetByFullnameOrEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - input string
func (_e *MockIUser_Expecter) GetByFullnameOrEmail(ctx interface{}, input interface{}) *MockIUser_GetByFullnameOrEmail_Call {
	return &MockIUser_GetByFullnameOrEmail_Call{Call: _e.mock.On("GetByFullnameOrEmail", ctx, input)}
}

func (_c *MockIUser_GetByFullnameOrEmail_Call) Run(run func(ctx context.Context, input string)) *MockIUser_GetByFullnameOrEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUser_GetByFullnameOrEmail_Call) Return(user *iampb.User, err error) *MockIUser_GetByFullnameOrEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUser_GetByFullnameOrEmail_Call) RunAndReturn(run func(ctx context.Context, input string) (*iampb.User, error)) *MockIUser_GetByFullnameOrEmail_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockIUser
func (_mock *MockIUser) List(ctx context.Context, req *iampb.ListUsersRequest) (*iampb.ListUsersResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *iampb.ListUsersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iampb.ListUsersRequest) (*iampb.ListUsersResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iampb.ListUsersRequest) *iampb.ListUsersResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iampb.ListUsersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *iampb.ListUsersRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUser_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIUser_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *iampb.ListUsersRequest
func (_e *MockIUser_Expecter) List(ctx interface{}, req interface{}) *MockIUser_List_Call {
	return &MockIUser_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockIUser_List_Call) Run(run func(ctx context.Context, req *iampb.ListUsersRequest)) *MockIUser_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *iampb.ListUsersRequest
		if args[1] != nil {
			arg1 = args[1].(*iampb.ListUsersRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUser_List_Call) Return(listUsersResponse *iampb.ListUsersResponse, err error) *MockIUser_List_Call {
	_c.Call.Return(listUsersResponse, err)
	return _c
}

func (_c *MockIUser_List_Call) RunAndReturn(run func(ctx context.Context, req *iampb.ListUsersRequest) (*iampb.ListUsersResponse, error)) *MockIUser_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIUser
func (_mock *MockIUser) Update(ctx context.Context, user *iampb.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iampb.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUser_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIUser_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *iampb.User
func (_e *MockIUser_Expecter) Update(ctx interface{}, user interface{}) *MockIUser_Update_Call {
	return &MockIUser_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockIUser_Update_Call) Run(run func(ctx context.Context, user *iampb.User)) *MockIUser_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *iampb.User
		if args[1] != nil {
			arg1 = args[1].(*iampb.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUser_Update_Call) Return(err error) *MockIUser_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUser_Update_Call) RunAndReturn(run func(ctx context.Context, user *iampb.User) error) *MockIUser_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTX provides a mock function for the type MockIUser
func (_mock *MockIUser) WithTX(tx *postgres.TxSession) usersrepo.IUser {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTX")
	}

	var r0 usersrepo.IUser
	if returnFunc, ok := ret.Get(0).(func(*postgres.TxSession) usersrepo.IUser); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(usersrepo.IUser)
		}
	}
	return r0
}

// MockIUser_WithTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTX'
type MockIUser_WithTX_Call struct {
	*mock.Call
}

// WithTX is a helper method to define mock.On call
//   - tx *postgres.TxSession
func (_e *MockIUser_Expecter) WithTX(tx interface{}) *MockIUser_WithTX_Call {
	return &MockIUser_WithTX_Call{Call: _e.mock.On("WithTX", tx)}
}

func (_c *MockIUser_WithTX_Call) Run(run func(tx *postgres.TxSession)) *MockIUser_WithTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *postgres.TxSession
		if args[0] != nil {
			arg0 = args[0].(*postgres.TxSession)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUser_WithTX_Call) Return(iUser usersrepo.IUser) *MockIUser_WithTX_Call {
	_c.Call.Return(iUser)
	return _c
}

func (_c *MockIUser_WithTX_Call) RunAndReturn(run func(tx *postgres.TxSession) usersrepo.IUser) *MockIUser_WithTX_Call {
	_c.Call.Return(run)
	return _c
}
