// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: sentinez/modules/security/v1/shared.proto

/* eslint-disable */

export const protobufPackage = "sentinez.modules.security.v1";
