// Copyright 2025 Duc-Hung Ho.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sentinez/apps/security/v1/security.proto

package securitypb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/sentinez/sentinez/api/proto/sentinez/types/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSecRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecRule       *SecRule               `protobuf:"bytes,1,opt,name=sec_rule,json=secRule,proto3" json:"sec_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecRuleRequest) Reset() {
	*x = CreateSecRuleRequest{}
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecRuleRequest) ProtoMessage() {}

func (x *CreateSecRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateSecRuleRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_apps_security_v1_security_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSecRuleRequest) GetSecRule() *SecRule {
	if x != nil {
		return x.SecRule
	}
	return nil
}

type CreateSecRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecRuleResponse) Reset() {
	*x = CreateSecRuleResponse{}
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecRuleResponse) ProtoMessage() {}

func (x *CreateSecRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateSecRuleResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_apps_security_v1_security_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSecRuleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSecRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecRuleRequest) Reset() {
	*x = GetSecRuleRequest{}
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecRuleRequest) ProtoMessage() {}

func (x *GetSecRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecRuleRequest.ProtoReflect.Descriptor instead.
func (*GetSecRuleRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_apps_security_v1_security_proto_rawDescGZIP(), []int{2}
}

func (x *GetSecRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSecRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecRule       *SecRule               `protobuf:"bytes,1,opt,name=sec_rule,json=secRule,proto3" json:"sec_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecRuleResponse) Reset() {
	*x = GetSecRuleResponse{}
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecRuleResponse) ProtoMessage() {}

func (x *GetSecRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecRuleResponse.ProtoReflect.Descriptor instead.
func (*GetSecRuleResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_apps_security_v1_security_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecRuleResponse) GetSecRule() *SecRule {
	if x != nil {
		return x.SecRule
	}
	return nil
}

type UpdateSecRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SecRule       *SecRule               `protobuf:"bytes,2,opt,name=sec_rule,json=secRule,proto3" json:"sec_rule,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecRuleRequest) Reset() {
	*x = UpdateSecRuleRequest{}
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecRuleRequest) ProtoMessage() {}

func (x *UpdateSecRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecRuleRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_apps_security_v1_security_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSecRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSecRuleRequest) GetSecRule() *SecRule {
	if x != nil {
		return x.SecRule
	}
	return nil
}

func (x *UpdateSecRuleRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateSecRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecRule       *SecRule               `protobuf:"bytes,1,opt,name=sec_rule,json=secRule,proto3" json:"sec_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecRuleResponse) Reset() {
	*x = UpdateSecRuleResponse{}
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecRuleResponse) ProtoMessage() {}

func (x *UpdateSecRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecRuleResponse.ProtoReflect.Descriptor instead.
func (*UpdateSecRuleResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_apps_security_v1_security_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSecRuleResponse) GetSecRule() *SecRule {
	if x != nil {
		return x.SecRule
	}
	return nil
}

type DeleteSecRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecRuleRequest) Reset() {
	*x = DeleteSecRuleRequest{}
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecRuleRequest) ProtoMessage() {}

func (x *DeleteSecRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecRuleRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_apps_security_v1_security_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSecRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSecRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecRuleResponse) Reset() {
	*x = DeleteSecRuleResponse{}
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecRuleResponse) ProtoMessage() {}

func (x *DeleteSecRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecRuleResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_apps_security_v1_security_proto_rawDescGZIP(), []int{7}
}

type ListSecRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.Pages              `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Ids           []string               `protobuf:"bytes,10,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecRulesRequest) Reset() {
	*x = ListSecRulesRequest{}
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecRulesRequest) ProtoMessage() {}

func (x *ListSecRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecRulesRequest.ProtoReflect.Descriptor instead.
func (*ListSecRulesRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_apps_security_v1_security_proto_rawDescGZIP(), []int{8}
}

func (x *ListSecRulesRequest) GetPage() *v1.Pages {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListSecRulesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListSecRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecRules      []*SecRule             `protobuf:"bytes,1,rep,name=sec_rules,json=secRules,proto3" json:"sec_rules,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecRulesResponse) Reset() {
	*x = ListSecRulesResponse{}
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecRulesResponse) ProtoMessage() {}

func (x *ListSecRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecRulesResponse.ProtoReflect.Descriptor instead.
func (*ListSecRulesResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_apps_security_v1_security_proto_rawDescGZIP(), []int{9}
}

func (x *ListSecRulesResponse) GetSecRules() []*SecRule {
	if x != nil {
		return x.SecRules
	}
	return nil
}

func (x *ListSecRulesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_apps_security_v1_security_proto_rawDescGZIP(), []int{10}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_apps_security_v1_security_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_apps_security_v1_security_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_sentinez_apps_security_v1_security_proto protoreflect.FileDescriptor

const file_sentinez_apps_security_v1_security_proto_rawDesc = "" +
	"\n" +
	"(sentinez/apps/security/v1/security.proto\x12\x19sentinez.apps.security.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a%sentinez/apps/security/v1/model.proto\x1a\x1dsentinez/types/v1/model.proto\x1a\x1fsentinez/types/v1/options.proto\"]\n" +
	"\x14CreateSecRuleRequest\x12E\n" +
	"\bsec_rule\x18\x01 \x01(\v2\".sentinez.apps.security.v1.SecRuleB\x06\xbaH\x03\xc8\x01\x01R\asecRule\"'\n" +
	"\x15CreateSecRuleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x11GetSecRuleRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"S\n" +
	"\x12GetSecRuleResponse\x12=\n" +
	"\bsec_rule\x18\x01 \x01(\v2\".sentinez.apps.security.v1.SecRuleR\asecRule\"\xb3\x01\n" +
	"\x14UpdateSecRuleRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12E\n" +
	"\bsec_rule\x18\x02 \x01(\v2\".sentinez.apps.security.v1.SecRuleB\x06\xbaH\x03\xc8\x01\x01R\asecRule\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"V\n" +
	"\x15UpdateSecRuleResponse\x12=\n" +
	"\bsec_rule\x18\x01 \x01(\v2\".sentinez.apps.security.v1.SecRuleR\asecRule\"/\n" +
	"\x14DeleteSecRuleRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"\x17\n" +
	"\x15DeleteSecRuleResponse\"U\n" +
	"\x13ListSecRulesRequest\x12,\n" +
	"\x04page\x18\x01 \x01(\v2\x18.sentinez.types.v1.PagesR\x04page\x12\x10\n" +
	"\x03ids\x18\n" +
	" \x03(\tR\x03ids\"m\n" +
	"\x14ListSecRulesResponse\x12?\n" +
	"\tsec_rules\x18\x01 \x03(\v2\".sentinez.apps.security.v1.SecRuleR\bsecRules\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x0f\n" +
	"\rStatusRequest\"\"\n" +
	"\x0eStatusResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\xea\x06\n" +
	"\x0fSecurityService\x12\x90\x01\n" +
	"\rCreateSecRule\x12/.sentinez.apps.security.v1.CreateSecRuleRequest\x1a0.sentinez.apps.security.v1.CreateSecRuleResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/security/secrule\x12\x89\x01\n" +
	"\n" +
	"GetSecRule\x12,.sentinez.apps.security.v1.GetSecRuleRequest\x1a-.sentinez.apps.security.v1.GetSecRuleResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/security/secrule/{id}\x12\x95\x01\n" +
	"\rUpdateSecRule\x12/.sentinez.apps.security.v1.UpdateSecRuleRequest\x1a0.sentinez.apps.security.v1.UpdateSecRuleResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/security/secrule/{id}\x12\x92\x01\n" +
	"\rDeleteSecRule\x12/.sentinez.apps.security.v1.DeleteSecRuleRequest\x1a0.sentinez.apps.security.v1.DeleteSecRuleResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/security/secrule/{id}\x12\x8b\x01\n" +
	"\fListSecRules\x12..sentinez.apps.security.v1.ListSecRulesRequest\x1a/.sentinez.apps.security.v1.ListSecRulesResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/security/secrules\x12}\n" +
	"\x06Status\x12(.sentinez.apps.security.v1.StatusRequest\x1a).sentinez.apps.security.v1.StatusResponse\"\x1e\x8a\xb5\x18\x02\b\x01\x82\xd3\xe4\x93\x02\x12\x12\x10/security/statusB\xed\x01\x92Af\x12\x17\n" +
	"\x10Security Service2\x031.0*\x02\x01\x022\x10application/jsonZ#\n" +
	"!\n" +
	"\n" +
	"ApiKeyAuth\x12\x13\b\x02\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"ApiKeyAuth\x12\x00\x8a\xb2\x193\n" +
	"\x14SENTINEZ // SECURITY\x10\x02\x1a\x19sentinez.apps.security.v1ZKgithub.com/sentinez/sentinez/api/proto/sentinez/apps/security/v1;securitypbb\x06proto3"

var (
	file_sentinez_apps_security_v1_security_proto_rawDescOnce sync.Once
	file_sentinez_apps_security_v1_security_proto_rawDescData []byte
)

func file_sentinez_apps_security_v1_security_proto_rawDescGZIP() []byte {
	file_sentinez_apps_security_v1_security_proto_rawDescOnce.Do(func() {
		file_sentinez_apps_security_v1_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinez_apps_security_v1_security_proto_rawDesc), len(file_sentinez_apps_security_v1_security_proto_rawDesc)))
	})
	return file_sentinez_apps_security_v1_security_proto_rawDescData
}

var file_sentinez_apps_security_v1_security_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sentinez_apps_security_v1_security_proto_goTypes = []any{
	(*CreateSecRuleRequest)(nil),  // 0: sentinez.apps.security.v1.CreateSecRuleRequest
	(*CreateSecRuleResponse)(nil), // 1: sentinez.apps.security.v1.CreateSecRuleResponse
	(*GetSecRuleRequest)(nil),     // 2: sentinez.apps.security.v1.GetSecRuleRequest
	(*GetSecRuleResponse)(nil),    // 3: sentinez.apps.security.v1.GetSecRuleResponse
	(*UpdateSecRuleRequest)(nil),  // 4: sentinez.apps.security.v1.UpdateSecRuleRequest
	(*UpdateSecRuleResponse)(nil), // 5: sentinez.apps.security.v1.UpdateSecRuleResponse
	(*DeleteSecRuleRequest)(nil),  // 6: sentinez.apps.security.v1.DeleteSecRuleRequest
	(*DeleteSecRuleResponse)(nil), // 7: sentinez.apps.security.v1.DeleteSecRuleResponse
	(*ListSecRulesRequest)(nil),   // 8: sentinez.apps.security.v1.ListSecRulesRequest
	(*ListSecRulesResponse)(nil),  // 9: sentinez.apps.security.v1.ListSecRulesResponse
	(*StatusRequest)(nil),         // 10: sentinez.apps.security.v1.StatusRequest
	(*StatusResponse)(nil),        // 11: sentinez.apps.security.v1.StatusResponse
	(*SecRule)(nil),               // 12: sentinez.apps.security.v1.SecRule
	(*fieldmaskpb.FieldMask)(nil), // 13: google.protobuf.FieldMask
	(*v1.Pages)(nil),              // 14: sentinez.types.v1.Pages
}
var file_sentinez_apps_security_v1_security_proto_depIdxs = []int32{
	12, // 0: sentinez.apps.security.v1.CreateSecRuleRequest.sec_rule:type_name -> sentinez.apps.security.v1.SecRule
	12, // 1: sentinez.apps.security.v1.GetSecRuleResponse.sec_rule:type_name -> sentinez.apps.security.v1.SecRule
	12, // 2: sentinez.apps.security.v1.UpdateSecRuleRequest.sec_rule:type_name -> sentinez.apps.security.v1.SecRule
	13, // 3: sentinez.apps.security.v1.UpdateSecRuleRequest.update_mask:type_name -> google.protobuf.FieldMask
	12, // 4: sentinez.apps.security.v1.UpdateSecRuleResponse.sec_rule:type_name -> sentinez.apps.security.v1.SecRule
	14, // 5: sentinez.apps.security.v1.ListSecRulesRequest.page:type_name -> sentinez.types.v1.Pages
	12, // 6: sentinez.apps.security.v1.ListSecRulesResponse.sec_rules:type_name -> sentinez.apps.security.v1.SecRule
	0,  // 7: sentinez.apps.security.v1.SecurityService.CreateSecRule:input_type -> sentinez.apps.security.v1.CreateSecRuleRequest
	2,  // 8: sentinez.apps.security.v1.SecurityService.GetSecRule:input_type -> sentinez.apps.security.v1.GetSecRuleRequest
	4,  // 9: sentinez.apps.security.v1.SecurityService.UpdateSecRule:input_type -> sentinez.apps.security.v1.UpdateSecRuleRequest
	6,  // 10: sentinez.apps.security.v1.SecurityService.DeleteSecRule:input_type -> sentinez.apps.security.v1.DeleteSecRuleRequest
	8,  // 11: sentinez.apps.security.v1.SecurityService.ListSecRules:input_type -> sentinez.apps.security.v1.ListSecRulesRequest
	10, // 12: sentinez.apps.security.v1.SecurityService.Status:input_type -> sentinez.apps.security.v1.StatusRequest
	1,  // 13: sentinez.apps.security.v1.SecurityService.CreateSecRule:output_type -> sentinez.apps.security.v1.CreateSecRuleResponse
	3,  // 14: sentinez.apps.security.v1.SecurityService.GetSecRule:output_type -> sentinez.apps.security.v1.GetSecRuleResponse
	5,  // 15: sentinez.apps.security.v1.SecurityService.UpdateSecRule:output_type -> sentinez.apps.security.v1.UpdateSecRuleResponse
	7,  // 16: sentinez.apps.security.v1.SecurityService.DeleteSecRule:output_type -> sentinez.apps.security.v1.DeleteSecRuleResponse
	9,  // 17: sentinez.apps.security.v1.SecurityService.ListSecRules:output_type -> sentinez.apps.security.v1.ListSecRulesResponse
	11, // 18: sentinez.apps.security.v1.SecurityService.Status:output_type -> sentinez.apps.security.v1.StatusResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_sentinez_apps_security_v1_security_proto_init() }
func file_sentinez_apps_security_v1_security_proto_init() {
	if File_sentinez_apps_security_v1_security_proto != nil {
		return
	}
	file_sentinez_apps_security_v1_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinez_apps_security_v1_security_proto_rawDesc), len(file_sentinez_apps_security_v1_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentinez_apps_security_v1_security_proto_goTypes,
		DependencyIndexes: file_sentinez_apps_security_v1_security_proto_depIdxs,
		MessageInfos:      file_sentinez_apps_security_v1_security_proto_msgTypes,
	}.Build()
	File_sentinez_apps_security_v1_security_proto = out.File
	file_sentinez_apps_security_v1_security_proto_goTypes = nil
	file_sentinez_apps_security_v1_security_proto_depIdxs = nil
}
