services:
  sentinez.redis:
    environment:
      - REDIS_HOST_PASSWORD=

  sentinez.postgres:
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=

  sentinez.edge:
    environment:
      - SNTZ_PUBLIC_EXAMPLE_1=
      - SNTZ_PUBLIC_EXAMPLE_2=

  sentinez.core.greeter.v1:
    environment:
      - SNTZ_PUBLIC_EXAMPLE_1=
      - SNTZ_PUBLIC_EXAMPLE_2=