package template

var SentinezRuleFunc = `
// Code generated by ruleparser-sentinez. DO NOT EDIT.
// Copyright 2025 Duc-Hung Ho
package rules

import (	
	"github.com/sentinez/sentinez/api/gen/go/sentinez/edge/waf/v1"
)

{{ $outer := . }}

const {{ .Name }}Version = {{ .Version | printf "%q" }}

var {{ .Name }} = map[string]*waf.Rule{
	{{- range .Rules }}
	{{- $ids := .Actions.Fields.Id }}
	{{- if $ids }}
	"{{ index $ids 0 }}": R{{ index $ids 0 }}(),
	{{- end }}
	{{- end }}
}

{{- range .Rules }}
{{- $rule := . }}
{{- $ids := .Actions.Fields.Id }}
{{- if $ids }}
// R{{ index $ids 0 }} returns rule with ID {{ index $ids 0 }}
func R{{ index $ids 0 }}() *waf.Rule {
	return &waf.Rule{
		Actions: &waf.RuleAction{
			Statement: {{ $rule.Actions.Statement | base64Encode | printf "%q" }},
			{{- if $rule.Actions.Fields }}
			Fields: &waf.RuleActionField{
				{{- if $rule.Actions.Fields.Id }}Id: []string{ {{ range $rule.Actions.Fields.Id }}{{ printf "%q" . }},{{ end }} },{{ end }}
				{{- if $rule.Actions.Fields.Msg }}Msg: []string{ {{ range $rule.Actions.Fields.Msg }}{{ printf "%q" . }},{{ end }} },{{ end }}
				{{- if $rule.Actions.Fields.Phase }}Phase: []string{ {{ range $rule.Actions.Fields.Phase }}{{ printf "%q" . }},{{ end }} },{{ end }}
				{{- if $rule.Actions.Fields.Tag }}Tag: []string{ {{ range $rule.Actions.Fields.Tag }}{{ printf "%q" . }},{{ end }} },{{ end }}
			},
			{{- end }}
		},
		Configuration: "{{ $rule.Configuration | base64Encode }}",
		Level: {{ $rule.Level | printf "%q" }},
	}
}
{{ end -}}
{{ end -}}

`
