// Copyright 2025 Duc-Hung Ho.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package sentinez.setting.v1;

import "sentinez/setting/v1/flags.proto";
import "sentinez/types/v1/options.proto";

option go_package = "github.com/sentinez/sentinez/api/proto/sentinez/setting/v1;settingpb";

enum Senz {
  SENZ_UNSPECIFIED = 0;
  SENZ_HOSTNAME = 1;       // hostname of service. eg s6z.io.vn
  SENZ_ADDRESS = 2;        // http address, api, application ...
  SENZ_SECRET_KEY = 3;     // secret key base64 encoded
  SENZ_CLIENT_ORIGIN = 4;  // origin of client, used to gen passkey
  SENZ_TIMESCALE_URI = 5;
  SENZ_POSTGRES_URI = 6;
  SENZ_CLICKHOUSE_URI = 7;
  SENZ_CONSUL_URI = 8;
  SENZ_MEMBERSHIP_ADDRESS = 9;
  SENZ_DISCOVERY_ADDRESS = 10;
}

message Config {
  sentinez.types.v1.XMeta meta = 1;
  sentinez.setting.v1.Flag flag = 2;
  map<string, string> env = 3;
}
