// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package accountrepo

import (
	"context"

	"github.com/sentinez/sentinez/api/gen/go/sentinez/core/iam/v1"
	"github.com/sentinez/sentinez/internal/core/iam/v1/repos/accounts"
	"github.com/sentinez/sentinez/pkg/infra/database/postgres"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIAccount creates a new instance of MockIAccount. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAccount(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAccount {
	mock := &MockIAccount{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAccount is an autogenerated mock type for the IAccount type
type MockIAccount struct {
	mock.Mock
}

type MockIAccount_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAccount) EXPECT() *MockIAccount_Expecter {
	return &MockIAccount_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIAccount
func (_mock *MockIAccount) Create(ctx context.Context, account *iam.Accounts) (*iam.Accounts, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *iam.Accounts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iam.Accounts) (*iam.Accounts, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iam.Accounts) *iam.Accounts); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iam.Accounts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *iam.Accounts) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccount_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAccount_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - account *iam.Accounts
func (_e *MockIAccount_Expecter) Create(ctx interface{}, account interface{}) *MockIAccount_Create_Call {
	return &MockIAccount_Create_Call{Call: _e.mock.On("Create", ctx, account)}
}

func (_c *MockIAccount_Create_Call) Run(run func(ctx context.Context, account *iam.Accounts)) *MockIAccount_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *iam.Accounts
		if args[1] != nil {
			arg1 = args[1].(*iam.Accounts)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccount_Create_Call) Return(accounts *iam.Accounts, err error) *MockIAccount_Create_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockIAccount_Create_Call) RunAndReturn(run func(ctx context.Context, account *iam.Accounts) (*iam.Accounts, error)) *MockIAccount_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIAccount
func (_mock *MockIAccount) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAccount_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIAccount_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIAccount_Expecter) Delete(ctx interface{}, id interface{}) *MockIAccount_Delete_Call {
	return &MockIAccount_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIAccount_Delete_Call) Run(run func(ctx context.Context, id string)) *MockIAccount_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccount_Delete_Call) Return(err error) *MockIAccount_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAccount_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIAccount_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockIAccount
func (_mock *MockIAccount) Get(ctx context.Context, id string) (*iam.Accounts, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *iam.Accounts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*iam.Accounts, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *iam.Accounts); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iam.Accounts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccount_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIAccount_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIAccount_Expecter) Get(ctx interface{}, id interface{}) *MockIAccount_Get_Call {
	return &MockIAccount_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockIAccount_Get_Call) Run(run func(ctx context.Context, id string)) *MockIAccount_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccount_Get_Call) Return(accounts *iam.Accounts, err error) *MockIAccount_Get_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockIAccount_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (*iam.Accounts, error)) *MockIAccount_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsernameOrEmail provides a mock function for the type MockIAccount
func (_mock *MockIAccount) GetByUsernameOrEmail(ctx context.Context, input string) (*iam.Accounts, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsernameOrEmail")
	}

	var r0 *iam.Accounts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*iam.Accounts, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *iam.Accounts); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iam.Accounts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccount_GetByUsernameOrEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsernameOrEmail'
type MockIAccount_GetByUsernameOrEmail_Call struct {
	*mock.Call
}

// GetByUsernameOrEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - input string
func (_e *MockIAccount_Expecter) GetByUsernameOrEmail(ctx interface{}, input interface{}) *MockIAccount_GetByUsernameOrEmail_Call {
	return &MockIAccount_GetByUsernameOrEmail_Call{Call: _e.mock.On("GetByUsernameOrEmail", ctx, input)}
}

func (_c *MockIAccount_GetByUsernameOrEmail_Call) Run(run func(ctx context.Context, input string)) *MockIAccount_GetByUsernameOrEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccount_GetByUsernameOrEmail_Call) Return(accounts *iam.Accounts, err error) *MockIAccount_GetByUsernameOrEmail_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockIAccount_GetByUsernameOrEmail_Call) RunAndReturn(run func(ctx context.Context, input string) (*iam.Accounts, error)) *MockIAccount_GetByUsernameOrEmail_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockIAccount
func (_mock *MockIAccount) List(ctx context.Context, req *iam.ListAccountsRequest) (*iam.ListAccountsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *iam.ListAccountsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iam.ListAccountsRequest) (*iam.ListAccountsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iam.ListAccountsRequest) *iam.ListAccountsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iam.ListAccountsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *iam.ListAccountsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccount_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIAccount_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *iam.ListAccountsRequest
func (_e *MockIAccount_Expecter) List(ctx interface{}, req interface{}) *MockIAccount_List_Call {
	return &MockIAccount_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockIAccount_List_Call) Run(run func(ctx context.Context, req *iam.ListAccountsRequest)) *MockIAccount_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *iam.ListAccountsRequest
		if args[1] != nil {
			arg1 = args[1].(*iam.ListAccountsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccount_List_Call) Return(listAccountsResponse *iam.ListAccountsResponse, err error) *MockIAccount_List_Call {
	_c.Call.Return(listAccountsResponse, err)
	return _c
}

func (_c *MockIAccount_List_Call) RunAndReturn(run func(ctx context.Context, req *iam.ListAccountsRequest) (*iam.ListAccountsResponse, error)) *MockIAccount_List_Call {
	_c.Call.Return(run)
	return _c
}

// Total provides a mock function for the type MockIAccount
func (_mock *MockIAccount) Total(ctx context.Context, req *iam.ListAccountsRequest) (int64, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Total")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iam.ListAccountsRequest) (int64, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iam.ListAccountsRequest) int64); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *iam.ListAccountsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccount_Total_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Total'
type MockIAccount_Total_Call struct {
	*mock.Call
}

// Total is a helper method to define mock.On call
//   - ctx context.Context
//   - req *iam.ListAccountsRequest
func (_e *MockIAccount_Expecter) Total(ctx interface{}, req interface{}) *MockIAccount_Total_Call {
	return &MockIAccount_Total_Call{Call: _e.mock.On("Total", ctx, req)}
}

func (_c *MockIAccount_Total_Call) Run(run func(ctx context.Context, req *iam.ListAccountsRequest)) *MockIAccount_Total_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *iam.ListAccountsRequest
		if args[1] != nil {
			arg1 = args[1].(*iam.ListAccountsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccount_Total_Call) Return(n int64, err error) *MockIAccount_Total_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIAccount_Total_Call) RunAndReturn(run func(ctx context.Context, req *iam.ListAccountsRequest) (int64, error)) *MockIAccount_Total_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIAccount
func (_mock *MockIAccount) Update(ctx context.Context, account *iam.Accounts) (*iam.Accounts, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *iam.Accounts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iam.Accounts) (*iam.Accounts, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iam.Accounts) *iam.Accounts); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iam.Accounts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *iam.Accounts) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccount_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIAccount_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - account *iam.Accounts
func (_e *MockIAccount_Expecter) Update(ctx interface{}, account interface{}) *MockIAccount_Update_Call {
	return &MockIAccount_Update_Call{Call: _e.mock.On("Update", ctx, account)}
}

func (_c *MockIAccount_Update_Call) Run(run func(ctx context.Context, account *iam.Accounts)) *MockIAccount_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *iam.Accounts
		if args[1] != nil {
			arg1 = args[1].(*iam.Accounts)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccount_Update_Call) Return(accounts *iam.Accounts, err error) *MockIAccount_Update_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockIAccount_Update_Call) RunAndReturn(run func(ctx context.Context, account *iam.Accounts) (*iam.Accounts, error)) *MockIAccount_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTX provides a mock function for the type MockIAccount
func (_mock *MockIAccount) WithTX(tx *postgres.TxSession) accountrepo.IAccount {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTX")
	}

	var r0 accountrepo.IAccount
	if returnFunc, ok := ret.Get(0).(func(*postgres.TxSession) accountrepo.IAccount); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(accountrepo.IAccount)
		}
	}
	return r0
}

// MockIAccount_WithTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTX'
type MockIAccount_WithTX_Call struct {
	*mock.Call
}

// WithTX is a helper method to define mock.On call
//   - tx *postgres.TxSession
func (_e *MockIAccount_Expecter) WithTX(tx interface{}) *MockIAccount_WithTX_Call {
	return &MockIAccount_WithTX_Call{Call: _e.mock.On("WithTX", tx)}
}

func (_c *MockIAccount_WithTX_Call) Run(run func(tx *postgres.TxSession)) *MockIAccount_WithTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *postgres.TxSession
		if args[0] != nil {
			arg0 = args[0].(*postgres.TxSession)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIAccount_WithTX_Call) Return(iAccount accountrepo.IAccount) *MockIAccount_WithTX_Call {
	_c.Call.Return(iAccount)
	return _c
}

func (_c *MockIAccount_WithTX_Call) RunAndReturn(run func(tx *postgres.TxSession) accountrepo.IAccount) *MockIAccount_WithTX_Call {
	_c.Call.Return(run)
	return _c
}
