// Code generated by protoc-gen-go-senz. DO NOT EDIT.
// Copyright 2025 Duc-Hung Ho

package apiserver

import (
	"fmt"

	typepb "github.com/sentinez/sentinez/api/proto/sentinez/types/v1"
	"google.golang.org/protobuf/proto"
)

var (
	_ typepb.Empty
	_ fmt.Stringer
	_ proto.Message
)

var metadata_apiserver = &typepb.XMeta{
	ServiceName: "SENTINEZ // APISERVER",
	ServiceZone: typepb.Zone_ZONE_PRIVATE_API,
	ServiceKey:  "sentinez.gateway.apiserver.v1",
}

func GetMetaApiserver() *typepb.XMeta {
	return proto.Clone(metadata_apiserver).(*typepb.XMeta)
}

func GetMetaApiserverServiceName() string {
	return metadata_apiserver.GetServiceName()
}

func GetMetaApiserverServiceZone() typepb.Zone {
	return metadata_apiserver.GetServiceZone()
}

func GetMetaApiserverServiceKey() string {
	return metadata_apiserver.GetServiceKey()
}
