// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DevSentinezUser struct {
	ID        string             `json:"id"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
