services:
  sentinez.dmz.edge:
    container_name: sentinez.dmz.edge
    hostname: sentinez.dmz.edge
    image: sentinez/edge:latest
    ports:
      - "7777:7777"
    networks:
      - sentinez-network

  sentinez.controlplane.greeter.v1:
    container_name: sentinez.controlplane.greeter.v1
    hostname: sentinez.controlplane.greeter.v1
    image: sentinez/greeter:latest
    networks:
      - sentinez-network

networks:
  sentinez-network:
    driver: bridge