// Copyright 2025 Duc-Hung Ho.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sentinez/modules/tenant/v1/tenant.proto

package tenantpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v11 "github.com/sentinez/sentinez/api/proto/sentinez/dmz/edge/v1"
	v1 "github.com/sentinez/sentinez/api/proto/sentinez/types/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Default       bool                   `protobuf:"varint,2,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *GetResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetResourceRequest) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

type GetResourceByDomainRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResourceDomain string                 `protobuf:"bytes,1,opt,name=resource_domain,json=resourceDomain,proto3" json:"resource_domain,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetResourceByDomainRequest) Reset() {
	*x = GetResourceByDomainRequest{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceByDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceByDomainRequest) ProtoMessage() {}

func (x *GetResourceByDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceByDomainRequest.ProtoReflect.Descriptor instead.
func (*GetResourceByDomainRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *GetResourceByDomainRequest) GetResourceDomain() string {
	if x != nil {
		return x.ResourceDomain
	}
	return ""
}

type GetResourceByDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceByDomainResponse) Reset() {
	*x = GetResourceByDomainResponse{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceByDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceByDomainResponse) ProtoMessage() {}

func (x *GetResourceByDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceByDomainResponse.ProtoReflect.Descriptor instead.
func (*GetResourceByDomainResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *GetResourceByDomainResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type GetResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceResponse) Reset() {
	*x = GetResourceResponse{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceResponse) ProtoMessage() {}

func (x *GetResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceResponse.ProtoReflect.Descriptor instead.
func (*GetResourceResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *GetResourceResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DeleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{5}
}

type UpdateResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResourceDomain string                 `protobuf:"bytes,2,opt,name=resource_domain,json=resourceDomain,proto3" json:"resource_domain,omitempty"`
	ResourceName   string                 `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Status         v1.Status              `protobuf:"varint,4,opt,name=status,proto3,enum=sentinez.types.v1.Status" json:"status,omitempty"`
	Plan           v1.Plan                `protobuf:"varint,5,opt,name=plan,proto3,enum=sentinez.types.v1.Plan" json:"plan,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateResourceRequest) Reset() {
	*x = UpdateResourceRequest{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceRequest) ProtoMessage() {}

func (x *UpdateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateResourceRequest) GetResourceDomain() string {
	if x != nil {
		return x.ResourceDomain
	}
	return ""
}

func (x *UpdateResourceRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *UpdateResourceRequest) GetStatus() v1.Status {
	if x != nil {
		return x.Status
	}
	return v1.Status(0)
}

func (x *UpdateResourceRequest) GetPlan() v1.Plan {
	if x != nil {
		return x.Plan
	}
	return v1.Plan(0)
}

type UpdateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceResponse) Reset() {
	*x = UpdateResourceResponse{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceResponse) ProtoMessage() {}

func (x *UpdateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceResponse.ProtoReflect.Descriptor instead.
func (*UpdateResourceResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{7}
}

type CreateResourceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResourceSetting *v11.Setting           `protobuf:"bytes,1,opt,name=resource_setting,json=resourceSetting,proto3" json:"resource_setting,omitempty"`
	ResourceDomain  string                 `protobuf:"bytes,2,opt,name=resource_domain,json=resourceDomain,proto3" json:"resource_domain,omitempty"`
	ResourceName    string                 `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Status          v1.Status              `protobuf:"varint,4,opt,name=status,proto3,enum=sentinez.types.v1.Status" json:"status,omitempty"`
	Plan            v1.Plan                `protobuf:"varint,5,opt,name=plan,proto3,enum=sentinez.types.v1.Plan" json:"plan,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *CreateResourceRequest) GetResourceSetting() *v11.Setting {
	if x != nil {
		return x.ResourceSetting
	}
	return nil
}

func (x *CreateResourceRequest) GetResourceDomain() string {
	if x != nil {
		return x.ResourceDomain
	}
	return ""
}

func (x *CreateResourceRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *CreateResourceRequest) GetStatus() v1.Status {
	if x != nil {
		return x.Status
	}
	return v1.Status(0)
}

func (x *CreateResourceRequest) GetPlan() v1.Plan {
	if x != nil {
		return x.Plan
	}
	return v1.Plan(0)
}

type CreateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceResponse) Reset() {
	*x = CreateResourceResponse{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceResponse) ProtoMessage() {}

func (x *CreateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceResponse.ProtoReflect.Descriptor instead.
func (*CreateResourceResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *CreateResourceResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ListResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           *v1.Pages              `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Status         v1.Status              `protobuf:"varint,2,opt,name=status,proto3,enum=sentinez.types.v1.Status" json:"status,omitempty"`
	Plan           v1.Plan                `protobuf:"varint,3,opt,name=plan,proto3,enum=sentinez.types.v1.Plan" json:"plan,omitempty"`
	ResourceName   string                 `protobuf:"bytes,4,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceDomain string                 `protobuf:"bytes,5,opt,name=resource_domain,json=resourceDomain,proto3" json:"resource_domain,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListResourceRequest) Reset() {
	*x = ListResourceRequest{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceRequest) ProtoMessage() {}

func (x *ListResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceRequest.ProtoReflect.Descriptor instead.
func (*ListResourceRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{10}
}

func (x *ListResourceRequest) GetPage() *v1.Pages {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListResourceRequest) GetStatus() v1.Status {
	if x != nil {
		return x.Status
	}
	return v1.Status(0)
}

func (x *ListResourceRequest) GetPlan() v1.Plan {
	if x != nil {
		return x.Plan
	}
	return v1.Plan(0)
}

func (x *ListResourceRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ListResourceRequest) GetResourceDomain() string {
	if x != nil {
		return x.ResourceDomain
	}
	return ""
}

type ListResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Resources     []*Resource            `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceResponse) Reset() {
	*x = ListResourceResponse{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceResponse) ProtoMessage() {}

func (x *ListResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceResponse.ProtoReflect.Descriptor instead.
func (*ListResourceResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{11}
}

func (x *ListResourceResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListResourceResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{12}
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_tenant_v1_tenant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP(), []int{13}
}

var File_sentinez_modules_tenant_v1_tenant_proto protoreflect.FileDescriptor

const file_sentinez_modules_tenant_v1_tenant_proto_rawDesc = "" +
	"\n" +
	"'sentinez/modules/tenant/v1/tenant.proto\x12\x1asentinez.modules.tenant.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a&sentinez/modules/tenant/v1/model.proto\x1a\"sentinez/dmz/edge/v1/setting.proto\x1a\x1dsentinez/types/v1/known.proto\x1a\x1dsentinez/types/v1/model.proto\x1a\x1fsentinez/types/v1/options.proto\"`\n" +
	"\x12GetResourceRequest\x120\n" +
	"\x02id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x00r\x18:\x16senz.tenant.resources.R\x02id\x12\x18\n" +
	"\adefault\x18\x02 \x01(\bR\adefault\"k\n" +
	"\x1aGetResourceByDomainRequest\x12M\n" +
	"\x0fresource_domain\x18\x01 \x01(\tB$\xbaH!r\x1f2\x1d^[a-zA-Z][a-zA-Z0-9._]{2,29}$R\x0eresourceDomain\"_\n" +
	"\x1bGetResourceByDomainResponse\x12@\n" +
	"\bresource\x18\x01 \x01(\v2$.sentinez.modules.tenant.v1.ResourceR\bresource\"W\n" +
	"\x13GetResourceResponse\x12@\n" +
	"\bresource\x18\x01 \x01(\v2$.sentinez.modules.tenant.v1.ResourceR\bresource\"I\n" +
	"\x15DeleteResourceRequest\x120\n" +
	"\x02id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18:\x16senz.tenant.resources.R\x02id\"\x18\n" +
	"\x16DeleteResourceResponse\"\xc3\x02\n" +
	"\x15UpdateResourceRequest\x120\n" +
	"\x02id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18:\x16senz.tenant.resources.R\x02id\x12M\n" +
	"\x0fresource_domain\x18\x02 \x01(\tB$\xbaH!r\x1f2\x1d^[a-zA-Z][a-zA-Z0-9._]{2,29}$R\x0eresourceDomain\x12I\n" +
	"\rresource_name\x18\x03 \x01(\tB$\xbaH!r\x1f2\x1d^[a-zA-Z][a-zA-Z0-9._]{2,29}$R\fresourceName\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.sentinez.types.v1.StatusR\x06status\x12+\n" +
	"\x04plan\x18\x05 \x01(\x0e2\x17.sentinez.types.v1.PlanR\x04plan\"\x18\n" +
	"\x16UpdateResourceResponse\"\xdb\x02\n" +
	"\x15CreateResourceRequest\x12H\n" +
	"\x10resource_setting\x18\x01 \x01(\v2\x1d.sentinez.dmz.edge.v1.SettingR\x0fresourceSetting\x12M\n" +
	"\x0fresource_domain\x18\x02 \x01(\tB$\xbaH!r\x1f2\x1d^[a-zA-Z][a-zA-Z0-9._]{2,29}$R\x0eresourceDomain\x12I\n" +
	"\rresource_name\x18\x03 \x01(\tB$\xbaH!r\x1f2\x1d^[a-zA-Z][a-zA-Z0-9._]{2,29}$R\fresourceName\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.sentinez.types.v1.StatusR\x06status\x12+\n" +
	"\x04plan\x18\x05 \x01(\x0e2\x17.sentinez.types.v1.PlanR\x04plan\"Z\n" +
	"\x16CreateResourceResponse\x12@\n" +
	"\bresource\x18\x01 \x01(\v2$.sentinez.modules.tenant.v1.ResourceR\bresource\"\xbd\x02\n" +
	"\x13ListResourceRequest\x12,\n" +
	"\x04page\x18\x01 \x01(\v2\x18.sentinez.types.v1.PagesR\x04page\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.sentinez.types.v1.StatusR\x06status\x12+\n" +
	"\x04plan\x18\x03 \x01(\x0e2\x17.sentinez.types.v1.PlanR\x04plan\x12I\n" +
	"\rresource_name\x18\x04 \x01(\tB$\xbaH!r\x1f2\x1d^[a-zA-Z][a-zA-Z0-9._]{2,29}$R\fresourceName\x12M\n" +
	"\x0fresource_domain\x18\x05 \x01(\tB$\xbaH!r\x1f2\x1d^[a-zA-Z][a-zA-Z0-9._]{2,29}$R\x0eresourceDomain\"p\n" +
	"\x14ListResourceResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12B\n" +
	"\tresources\x18\x02 \x03(\v2$.sentinez.modules.tenant.v1.ResourceR\tresources\"*\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x0f\n" +
	"\rStatusRequest2\xcf\b\n" +
	"\rTenantService\x12}\n" +
	"\x06Status\x12).sentinez.modules.tenant.v1.StatusRequest\x1a*.sentinez.modules.tenant.v1.StatusResponse\"\x1c\x8a\xb5\x18\x02\b\x01\x82\xd3\xe4\x93\x02\x10\x12\x0e/tenant/status\x12\x94\x01\n" +
	"\fListResource\x12/.sentinez.modules.tenant.v1.ListResourceRequest\x1a0.sentinez.modules.tenant.v1.ListResourceResponse\"!\x8a\xb5\x18\x04\x12\x02\x01\x02\x82\xd3\xe4\x93\x02\x13\x12\x11/tenant/resources\x12\x9c\x01\n" +
	"\x0eCreateResource\x121.sentinez.modules.tenant.v1.CreateResourceRequest\x1a2.sentinez.modules.tenant.v1.CreateResourceResponse\"#\x8a\xb5\x18\x04\x12\x02\x01\x02\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/tenant/resource\x12\x9c\x01\n" +
	"\x0eUpdateResource\x121.sentinez.modules.tenant.v1.UpdateResourceRequest\x1a2.sentinez.modules.tenant.v1.UpdateResourceResponse\"#\x8a\xb5\x18\x04\x12\x02\x01\x02\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/tenant/resource\x12\x99\x01\n" +
	"\x0eDeleteResource\x121.sentinez.modules.tenant.v1.DeleteResourceRequest\x1a2.sentinez.modules.tenant.v1.DeleteResourceResponse\" \x8a\xb5\x18\x04\x12\x02\x01\x02\x82\xd3\xe4\x93\x02\x12*\x10/tenant/resource\x12\x90\x01\n" +
	"\vGetResource\x12..sentinez.modules.tenant.v1.GetResourceRequest\x1a/.sentinez.modules.tenant.v1.GetResourceResponse\" \x8a\xb5\x18\x04\x12\x02\x01\x02\x82\xd3\xe4\x93\x02\x12\x12\x10/tenant/resource\x12\xba\x01\n" +
	"\x13GetResourceByDomain\x126.sentinez.modules.tenant.v1.GetResourceByDomainRequest\x1a7.sentinez.modules.tenant.v1.GetResourceByDomainResponse\"2\x8a\xb5\x18\x04\x12\x02\x01\x02\x82\xd3\xe4\x93\x02$\x12\"/tenant/resource/{resource_domain}B\xe9\x01\x92Ad\x12\x15\n" +
	"\x0eTenant Service2\x031.0*\x02\x01\x022\x10application/jsonZ#\n" +
	"!\n" +
	"\n" +
	"ApiKeyAuth\x12\x13\b\x02\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"ApiKeyAuth\x12\x00\x8a\xb2\x192\n" +
	"\x12SENTINEZ // TENANT\x10\x04\x1a\x1asentinez.modules.tenant.v1ZJgithub.com/sentinez/sentinez/api/proto/sentinez/modules/tenant/v1;tenantpbb\x06proto3"

var (
	file_sentinez_modules_tenant_v1_tenant_proto_rawDescOnce sync.Once
	file_sentinez_modules_tenant_v1_tenant_proto_rawDescData []byte
)

func file_sentinez_modules_tenant_v1_tenant_proto_rawDescGZIP() []byte {
	file_sentinez_modules_tenant_v1_tenant_proto_rawDescOnce.Do(func() {
		file_sentinez_modules_tenant_v1_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinez_modules_tenant_v1_tenant_proto_rawDesc), len(file_sentinez_modules_tenant_v1_tenant_proto_rawDesc)))
	})
	return file_sentinez_modules_tenant_v1_tenant_proto_rawDescData
}

var file_sentinez_modules_tenant_v1_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_sentinez_modules_tenant_v1_tenant_proto_goTypes = []any{
	(*GetResourceRequest)(nil),          // 0: sentinez.modules.tenant.v1.GetResourceRequest
	(*GetResourceByDomainRequest)(nil),  // 1: sentinez.modules.tenant.v1.GetResourceByDomainRequest
	(*GetResourceByDomainResponse)(nil), // 2: sentinez.modules.tenant.v1.GetResourceByDomainResponse
	(*GetResourceResponse)(nil),         // 3: sentinez.modules.tenant.v1.GetResourceResponse
	(*DeleteResourceRequest)(nil),       // 4: sentinez.modules.tenant.v1.DeleteResourceRequest
	(*DeleteResourceResponse)(nil),      // 5: sentinez.modules.tenant.v1.DeleteResourceResponse
	(*UpdateResourceRequest)(nil),       // 6: sentinez.modules.tenant.v1.UpdateResourceRequest
	(*UpdateResourceResponse)(nil),      // 7: sentinez.modules.tenant.v1.UpdateResourceResponse
	(*CreateResourceRequest)(nil),       // 8: sentinez.modules.tenant.v1.CreateResourceRequest
	(*CreateResourceResponse)(nil),      // 9: sentinez.modules.tenant.v1.CreateResourceResponse
	(*ListResourceRequest)(nil),         // 10: sentinez.modules.tenant.v1.ListResourceRequest
	(*ListResourceResponse)(nil),        // 11: sentinez.modules.tenant.v1.ListResourceResponse
	(*StatusResponse)(nil),              // 12: sentinez.modules.tenant.v1.StatusResponse
	(*StatusRequest)(nil),               // 13: sentinez.modules.tenant.v1.StatusRequest
	(*Resource)(nil),                    // 14: sentinez.modules.tenant.v1.Resource
	(v1.Status)(0),                      // 15: sentinez.types.v1.Status
	(v1.Plan)(0),                        // 16: sentinez.types.v1.Plan
	(*v11.Setting)(nil),                 // 17: sentinez.dmz.edge.v1.Setting
	(*v1.Pages)(nil),                    // 18: sentinez.types.v1.Pages
}
var file_sentinez_modules_tenant_v1_tenant_proto_depIdxs = []int32{
	14, // 0: sentinez.modules.tenant.v1.GetResourceByDomainResponse.resource:type_name -> sentinez.modules.tenant.v1.Resource
	14, // 1: sentinez.modules.tenant.v1.GetResourceResponse.resource:type_name -> sentinez.modules.tenant.v1.Resource
	15, // 2: sentinez.modules.tenant.v1.UpdateResourceRequest.status:type_name -> sentinez.types.v1.Status
	16, // 3: sentinez.modules.tenant.v1.UpdateResourceRequest.plan:type_name -> sentinez.types.v1.Plan
	17, // 4: sentinez.modules.tenant.v1.CreateResourceRequest.resource_setting:type_name -> sentinez.dmz.edge.v1.Setting
	15, // 5: sentinez.modules.tenant.v1.CreateResourceRequest.status:type_name -> sentinez.types.v1.Status
	16, // 6: sentinez.modules.tenant.v1.CreateResourceRequest.plan:type_name -> sentinez.types.v1.Plan
	14, // 7: sentinez.modules.tenant.v1.CreateResourceResponse.resource:type_name -> sentinez.modules.tenant.v1.Resource
	18, // 8: sentinez.modules.tenant.v1.ListResourceRequest.page:type_name -> sentinez.types.v1.Pages
	15, // 9: sentinez.modules.tenant.v1.ListResourceRequest.status:type_name -> sentinez.types.v1.Status
	16, // 10: sentinez.modules.tenant.v1.ListResourceRequest.plan:type_name -> sentinez.types.v1.Plan
	14, // 11: sentinez.modules.tenant.v1.ListResourceResponse.resources:type_name -> sentinez.modules.tenant.v1.Resource
	13, // 12: sentinez.modules.tenant.v1.TenantService.Status:input_type -> sentinez.modules.tenant.v1.StatusRequest
	10, // 13: sentinez.modules.tenant.v1.TenantService.ListResource:input_type -> sentinez.modules.tenant.v1.ListResourceRequest
	8,  // 14: sentinez.modules.tenant.v1.TenantService.CreateResource:input_type -> sentinez.modules.tenant.v1.CreateResourceRequest
	6,  // 15: sentinez.modules.tenant.v1.TenantService.UpdateResource:input_type -> sentinez.modules.tenant.v1.UpdateResourceRequest
	4,  // 16: sentinez.modules.tenant.v1.TenantService.DeleteResource:input_type -> sentinez.modules.tenant.v1.DeleteResourceRequest
	0,  // 17: sentinez.modules.tenant.v1.TenantService.GetResource:input_type -> sentinez.modules.tenant.v1.GetResourceRequest
	1,  // 18: sentinez.modules.tenant.v1.TenantService.GetResourceByDomain:input_type -> sentinez.modules.tenant.v1.GetResourceByDomainRequest
	12, // 19: sentinez.modules.tenant.v1.TenantService.Status:output_type -> sentinez.modules.tenant.v1.StatusResponse
	11, // 20: sentinez.modules.tenant.v1.TenantService.ListResource:output_type -> sentinez.modules.tenant.v1.ListResourceResponse
	9,  // 21: sentinez.modules.tenant.v1.TenantService.CreateResource:output_type -> sentinez.modules.tenant.v1.CreateResourceResponse
	7,  // 22: sentinez.modules.tenant.v1.TenantService.UpdateResource:output_type -> sentinez.modules.tenant.v1.UpdateResourceResponse
	5,  // 23: sentinez.modules.tenant.v1.TenantService.DeleteResource:output_type -> sentinez.modules.tenant.v1.DeleteResourceResponse
	3,  // 24: sentinez.modules.tenant.v1.TenantService.GetResource:output_type -> sentinez.modules.tenant.v1.GetResourceResponse
	2,  // 25: sentinez.modules.tenant.v1.TenantService.GetResourceByDomain:output_type -> sentinez.modules.tenant.v1.GetResourceByDomainResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_sentinez_modules_tenant_v1_tenant_proto_init() }
func file_sentinez_modules_tenant_v1_tenant_proto_init() {
	if File_sentinez_modules_tenant_v1_tenant_proto != nil {
		return
	}
	file_sentinez_modules_tenant_v1_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinez_modules_tenant_v1_tenant_proto_rawDesc), len(file_sentinez_modules_tenant_v1_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentinez_modules_tenant_v1_tenant_proto_goTypes,
		DependencyIndexes: file_sentinez_modules_tenant_v1_tenant_proto_depIdxs,
		MessageInfos:      file_sentinez_modules_tenant_v1_tenant_proto_msgTypes,
	}.Build()
	File_sentinez_modules_tenant_v1_tenant_proto = out.File
	file_sentinez_modules_tenant_v1_tenant_proto_goTypes = nil
	file_sentinez_modules_tenant_v1_tenant_proto_depIdxs = nil
}
