// Copyright 2025 Duc-Hung Ho.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package sentinez.edge.v1;

import "sentinez/types/rule/engine/v1/ruleengine.proto";

option go_package = "github.com/sentinez/sentinez/api/gen/go/sentinez/edge/v1;edgepb";

// Context represents the essential information extracted from an HTTP request.
message RequestContext {
  string                    id             = 1;
  bytes                     body           = 2; // Raw request body
  map<string, string>       header         = 3; // HTTP headers
  string                    host           = 4; // Hostname or domain
  string                    ip             = 5; // Client IP address
  string                    ja4            = 6; // JA4 fingerprint
  string                    method         = 7; // HTTP method (GET, POST, etc.)
  string                    path           = 8; // Request path
  map<string, RequestQuery> queries        = 9; // Query parameters
  bool                      tls            = 10; // Whether the connection used TLS
  string                    protocol       = 11;
  string                    remote_address = 12;
  int32                     status_code    = 13;
  string                    uri            = 14;
}

message RequestQuery {
  repeated string value = 1;
}

service EdgeEngineService {

  rpc EvaluateIngress(EvaluateIngressRequest) returns (EvaluateIngressResponse);
}

message EvaluateIngressRequest {
  string         ruleset_id      = 1;
  RequestContext request_context = 2;
}

message EvaluationResult {
  string                                        rule_id = 1;
  bool                                          matched = 2;
  repeated sentinez.types.rule.engine.v1.Action actions = 3;
}

message EvaluateIngressResponse { repeated EvaluationResult results = 1; }
