// Copyright 2025 Duc-Hung Ho.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sentinez/modules/security/v1/security.proto

package securitypb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/sentinez/sentinez/api/proto/sentinez/types/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRuleBasedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleBased     *RuleBased             `protobuf:"bytes,1,opt,name=rule_based,json=ruleBased,proto3" json:"rule_based,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleBasedRequest) Reset() {
	*x = CreateRuleBasedRequest{}
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleBasedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleBasedRequest) ProtoMessage() {}

func (x *CreateRuleBasedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleBasedRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleBasedRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_security_v1_security_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRuleBasedRequest) GetRuleBased() *RuleBased {
	if x != nil {
		return x.RuleBased
	}
	return nil
}

type CreateRuleBasedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleBasedResponse) Reset() {
	*x = CreateRuleBasedResponse{}
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleBasedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleBasedResponse) ProtoMessage() {}

func (x *CreateRuleBasedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleBasedResponse.ProtoReflect.Descriptor instead.
func (*CreateRuleBasedResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_security_v1_security_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRuleBasedResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRuleBasedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleBasedRequest) Reset() {
	*x = GetRuleBasedRequest{}
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleBasedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleBasedRequest) ProtoMessage() {}

func (x *GetRuleBasedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleBasedRequest.ProtoReflect.Descriptor instead.
func (*GetRuleBasedRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_security_v1_security_proto_rawDescGZIP(), []int{2}
}

func (x *GetRuleBasedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRuleBasedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleBased     *RuleBased             `protobuf:"bytes,1,opt,name=rule_based,json=ruleBased,proto3" json:"rule_based,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleBasedResponse) Reset() {
	*x = GetRuleBasedResponse{}
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleBasedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleBasedResponse) ProtoMessage() {}

func (x *GetRuleBasedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleBasedResponse.ProtoReflect.Descriptor instead.
func (*GetRuleBasedResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_security_v1_security_proto_rawDescGZIP(), []int{3}
}

func (x *GetRuleBasedResponse) GetRuleBased() *RuleBased {
	if x != nil {
		return x.RuleBased
	}
	return nil
}

type UpdateRuleBasedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleBased     *RuleBased             `protobuf:"bytes,2,opt,name=rule_based,json=ruleBased,proto3" json:"rule_based,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleBasedRequest) Reset() {
	*x = UpdateRuleBasedRequest{}
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleBasedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleBasedRequest) ProtoMessage() {}

func (x *UpdateRuleBasedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleBasedRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuleBasedRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_security_v1_security_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRuleBasedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRuleBasedRequest) GetRuleBased() *RuleBased {
	if x != nil {
		return x.RuleBased
	}
	return nil
}

func (x *UpdateRuleBasedRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateRuleBasedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleBased     *RuleBased             `protobuf:"bytes,1,opt,name=rule_based,json=ruleBased,proto3" json:"rule_based,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleBasedResponse) Reset() {
	*x = UpdateRuleBasedResponse{}
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleBasedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleBasedResponse) ProtoMessage() {}

func (x *UpdateRuleBasedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleBasedResponse.ProtoReflect.Descriptor instead.
func (*UpdateRuleBasedResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_security_v1_security_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRuleBasedResponse) GetRuleBased() *RuleBased {
	if x != nil {
		return x.RuleBased
	}
	return nil
}

type DeleteRuleBasedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleBasedRequest) Reset() {
	*x = DeleteRuleBasedRequest{}
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleBasedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleBasedRequest) ProtoMessage() {}

func (x *DeleteRuleBasedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleBasedRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleBasedRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_security_v1_security_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRuleBasedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRuleBasedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleBasedResponse) Reset() {
	*x = DeleteRuleBasedResponse{}
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleBasedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleBasedResponse) ProtoMessage() {}

func (x *DeleteRuleBasedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleBasedResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuleBasedResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_security_v1_security_proto_rawDescGZIP(), []int{7}
}

type ListRuleBasedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.Pages              `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Ids           []string               `protobuf:"bytes,10,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuleBasedsRequest) Reset() {
	*x = ListRuleBasedsRequest{}
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuleBasedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuleBasedsRequest) ProtoMessage() {}

func (x *ListRuleBasedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuleBasedsRequest.ProtoReflect.Descriptor instead.
func (*ListRuleBasedsRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_security_v1_security_proto_rawDescGZIP(), []int{8}
}

func (x *ListRuleBasedsRequest) GetPage() *v1.Pages {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListRuleBasedsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListRuleBasedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleBaseds    []*RuleBased           `protobuf:"bytes,1,rep,name=rule_baseds,json=ruleBaseds,proto3" json:"rule_baseds,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuleBasedsResponse) Reset() {
	*x = ListRuleBasedsResponse{}
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuleBasedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuleBasedsResponse) ProtoMessage() {}

func (x *ListRuleBasedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuleBasedsResponse.ProtoReflect.Descriptor instead.
func (*ListRuleBasedsResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_security_v1_security_proto_rawDescGZIP(), []int{9}
}

func (x *ListRuleBasedsResponse) GetRuleBaseds() []*RuleBased {
	if x != nil {
		return x.RuleBaseds
	}
	return nil
}

func (x *ListRuleBasedsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_security_v1_security_proto_rawDescGZIP(), []int{10}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_modules_security_v1_security_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_sentinez_modules_security_v1_security_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_sentinez_modules_security_v1_security_proto protoreflect.FileDescriptor

const file_sentinez_modules_security_v1_security_proto_rawDesc = "" +
	"\n" +
	"+sentinez/modules/security/v1/security.proto\x12\x1csentinez.modules.security.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a(sentinez/modules/security/v1/model.proto\x1a\x1dsentinez/types/v1/model.proto\x1a\x1fsentinez/types/v1/options.proto\"h\n" +
	"\x16CreateRuleBasedRequest\x12N\n" +
	"\n" +
	"rule_based\x18\x01 \x01(\v2'.sentinez.modules.security.v1.RuleBasedB\x06\xbaH\x03\xc8\x01\x01R\truleBased\")\n" +
	"\x17CreateRuleBasedResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x13GetRuleBasedRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"^\n" +
	"\x14GetRuleBasedResponse\x12F\n" +
	"\n" +
	"rule_based\x18\x01 \x01(\v2'.sentinez.modules.security.v1.RuleBasedR\truleBased\"\xbe\x01\n" +
	"\x16UpdateRuleBasedRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12N\n" +
	"\n" +
	"rule_based\x18\x02 \x01(\v2'.sentinez.modules.security.v1.RuleBasedB\x06\xbaH\x03\xc8\x01\x01R\truleBased\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"a\n" +
	"\x17UpdateRuleBasedResponse\x12F\n" +
	"\n" +
	"rule_based\x18\x01 \x01(\v2'.sentinez.modules.security.v1.RuleBasedR\truleBased\"1\n" +
	"\x16DeleteRuleBasedRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"\x19\n" +
	"\x17DeleteRuleBasedResponse\"W\n" +
	"\x15ListRuleBasedsRequest\x12,\n" +
	"\x04page\x18\x01 \x01(\v2\x18.sentinez.types.v1.PagesR\x04page\x12\x10\n" +
	"\x03ids\x18\n" +
	" \x03(\tR\x03ids\"x\n" +
	"\x16ListRuleBasedsResponse\x12H\n" +
	"\vrule_baseds\x18\x01 \x03(\v2'.sentinez.modules.security.v1.RuleBasedR\n" +
	"ruleBaseds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x0f\n" +
	"\rStatusRequest\"\"\n" +
	"\x0eStatusResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\xb7\a\n" +
	"\x0fSecurityService\x12\x9e\x01\n" +
	"\x0fCreateRuleBased\x124.sentinez.modules.security.v1.CreateRuleBasedRequest\x1a5.sentinez.modules.security.v1.CreateRuleBasedResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/security/rulebased\x12\x97\x01\n" +
	"\fGetRuleBased\x121.sentinez.modules.security.v1.GetRuleBasedRequest\x1a2.sentinez.modules.security.v1.GetRuleBasedResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/security/rulebased/{id}\x12\xa3\x01\n" +
	"\x0fUpdateRuleBased\x124.sentinez.modules.security.v1.UpdateRuleBasedRequest\x1a5.sentinez.modules.security.v1.UpdateRuleBasedResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/security/rulebased/{id}\x12\xa0\x01\n" +
	"\x0fDeleteRuleBased\x124.sentinez.modules.security.v1.DeleteRuleBasedRequest\x1a5.sentinez.modules.security.v1.DeleteRuleBasedResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/security/rulebased/{id}\x12\x99\x01\n" +
	"\x0eListRuleBaseds\x123.sentinez.modules.security.v1.ListRuleBasedsRequest\x1a4.sentinez.modules.security.v1.ListRuleBasedsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/security/rulebaseds\x12\x83\x01\n" +
	"\x06Status\x12+.sentinez.modules.security.v1.StatusRequest\x1a,.sentinez.modules.security.v1.StatusResponse\"\x1e\x8a\xb5\x18\x02\b\x01\x82\xd3\xe4\x93\x02\x12\x12\x10/security/statusB\xf3\x01\x92Af\x12\x17\n" +
	"\x10Security Service2\x031.0*\x02\x01\x022\x10application/jsonZ#\n" +
	"!\n" +
	"\n" +
	"ApiKeyAuth\x12\x13\b\x02\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"ApiKeyAuth\x12\x00\x8a\xb2\x196\n" +
	"\x14SENTINEZ // SECURITY\x10\x04\x1a\x1csentinez.modules.security.v1ZNgithub.com/sentinez/sentinez/api/proto/sentinez/modules/security/v1;securitypbb\x06proto3"

var (
	file_sentinez_modules_security_v1_security_proto_rawDescOnce sync.Once
	file_sentinez_modules_security_v1_security_proto_rawDescData []byte
)

func file_sentinez_modules_security_v1_security_proto_rawDescGZIP() []byte {
	file_sentinez_modules_security_v1_security_proto_rawDescOnce.Do(func() {
		file_sentinez_modules_security_v1_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinez_modules_security_v1_security_proto_rawDesc), len(file_sentinez_modules_security_v1_security_proto_rawDesc)))
	})
	return file_sentinez_modules_security_v1_security_proto_rawDescData
}

var file_sentinez_modules_security_v1_security_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sentinez_modules_security_v1_security_proto_goTypes = []any{
	(*CreateRuleBasedRequest)(nil),  // 0: sentinez.modules.security.v1.CreateRuleBasedRequest
	(*CreateRuleBasedResponse)(nil), // 1: sentinez.modules.security.v1.CreateRuleBasedResponse
	(*GetRuleBasedRequest)(nil),     // 2: sentinez.modules.security.v1.GetRuleBasedRequest
	(*GetRuleBasedResponse)(nil),    // 3: sentinez.modules.security.v1.GetRuleBasedResponse
	(*UpdateRuleBasedRequest)(nil),  // 4: sentinez.modules.security.v1.UpdateRuleBasedRequest
	(*UpdateRuleBasedResponse)(nil), // 5: sentinez.modules.security.v1.UpdateRuleBasedResponse
	(*DeleteRuleBasedRequest)(nil),  // 6: sentinez.modules.security.v1.DeleteRuleBasedRequest
	(*DeleteRuleBasedResponse)(nil), // 7: sentinez.modules.security.v1.DeleteRuleBasedResponse
	(*ListRuleBasedsRequest)(nil),   // 8: sentinez.modules.security.v1.ListRuleBasedsRequest
	(*ListRuleBasedsResponse)(nil),  // 9: sentinez.modules.security.v1.ListRuleBasedsResponse
	(*StatusRequest)(nil),           // 10: sentinez.modules.security.v1.StatusRequest
	(*StatusResponse)(nil),          // 11: sentinez.modules.security.v1.StatusResponse
	(*RuleBased)(nil),               // 12: sentinez.modules.security.v1.RuleBased
	(*fieldmaskpb.FieldMask)(nil),   // 13: google.protobuf.FieldMask
	(*v1.Pages)(nil),                // 14: sentinez.types.v1.Pages
}
var file_sentinez_modules_security_v1_security_proto_depIdxs = []int32{
	12, // 0: sentinez.modules.security.v1.CreateRuleBasedRequest.rule_based:type_name -> sentinez.modules.security.v1.RuleBased
	12, // 1: sentinez.modules.security.v1.GetRuleBasedResponse.rule_based:type_name -> sentinez.modules.security.v1.RuleBased
	12, // 2: sentinez.modules.security.v1.UpdateRuleBasedRequest.rule_based:type_name -> sentinez.modules.security.v1.RuleBased
	13, // 3: sentinez.modules.security.v1.UpdateRuleBasedRequest.update_mask:type_name -> google.protobuf.FieldMask
	12, // 4: sentinez.modules.security.v1.UpdateRuleBasedResponse.rule_based:type_name -> sentinez.modules.security.v1.RuleBased
	14, // 5: sentinez.modules.security.v1.ListRuleBasedsRequest.page:type_name -> sentinez.types.v1.Pages
	12, // 6: sentinez.modules.security.v1.ListRuleBasedsResponse.rule_baseds:type_name -> sentinez.modules.security.v1.RuleBased
	0,  // 7: sentinez.modules.security.v1.SecurityService.CreateRuleBased:input_type -> sentinez.modules.security.v1.CreateRuleBasedRequest
	2,  // 8: sentinez.modules.security.v1.SecurityService.GetRuleBased:input_type -> sentinez.modules.security.v1.GetRuleBasedRequest
	4,  // 9: sentinez.modules.security.v1.SecurityService.UpdateRuleBased:input_type -> sentinez.modules.security.v1.UpdateRuleBasedRequest
	6,  // 10: sentinez.modules.security.v1.SecurityService.DeleteRuleBased:input_type -> sentinez.modules.security.v1.DeleteRuleBasedRequest
	8,  // 11: sentinez.modules.security.v1.SecurityService.ListRuleBaseds:input_type -> sentinez.modules.security.v1.ListRuleBasedsRequest
	10, // 12: sentinez.modules.security.v1.SecurityService.Status:input_type -> sentinez.modules.security.v1.StatusRequest
	1,  // 13: sentinez.modules.security.v1.SecurityService.CreateRuleBased:output_type -> sentinez.modules.security.v1.CreateRuleBasedResponse
	3,  // 14: sentinez.modules.security.v1.SecurityService.GetRuleBased:output_type -> sentinez.modules.security.v1.GetRuleBasedResponse
	5,  // 15: sentinez.modules.security.v1.SecurityService.UpdateRuleBased:output_type -> sentinez.modules.security.v1.UpdateRuleBasedResponse
	7,  // 16: sentinez.modules.security.v1.SecurityService.DeleteRuleBased:output_type -> sentinez.modules.security.v1.DeleteRuleBasedResponse
	9,  // 17: sentinez.modules.security.v1.SecurityService.ListRuleBaseds:output_type -> sentinez.modules.security.v1.ListRuleBasedsResponse
	11, // 18: sentinez.modules.security.v1.SecurityService.Status:output_type -> sentinez.modules.security.v1.StatusResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_sentinez_modules_security_v1_security_proto_init() }
func file_sentinez_modules_security_v1_security_proto_init() {
	if File_sentinez_modules_security_v1_security_proto != nil {
		return
	}
	file_sentinez_modules_security_v1_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinez_modules_security_v1_security_proto_rawDesc), len(file_sentinez_modules_security_v1_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentinez_modules_security_v1_security_proto_goTypes,
		DependencyIndexes: file_sentinez_modules_security_v1_security_proto_depIdxs,
		MessageInfos:      file_sentinez_modules_security_v1_security_proto_msgTypes,
	}.Build()
	File_sentinez_modules_security_v1_security_proto = out.File
	file_sentinez_modules_security_v1_security_proto_goTypes = nil
	file_sentinez_modules_security_v1_security_proto_depIdxs = nil
}
