name: CI / Sync Git Repo

permissions:
  contents: write

on:
  push:
    branches:
      - staging
      - main

jobs:
  sync:
    name: Run sync repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config user.name "Duc-Hung Ho"
          git config user.email "iduchungho@gmail.com"

      - name: Add permission to script
        run: |
          chmod +x ./hack/git/staging-ci
      
      - name: Sync git repo - Core
        run: |
          TOKEN=${{ secrets.SENZ_GITHUB_TOKEN }}
          REMOTE=https://kyerans:${TOKEN}@github.com/sentinez/core.git
          NAME="core"

          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          PREFIX="staging/src/github.com/sentinez/${NAME}"
          BRANCH="$CURRENT_BRANCH"

          echo "MODULE:   $NAME"
          echo "REMOTE:   $REMOTE"
          echo "PREFIX:   $PREFIX"
          echo "BRANCH:   $BRANCH"
          echo

          echo "Pushing subtree '$PREFIX' to remote '$REMOTE' on branch '$BRANCH'..."

          git fetch "$REMOTE" "$BRANCH"
          
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | \
              xargs -L1 git config --unset-all

          git subtree push --prefix="$PREFIX" "$REMOTE" "$BRANCH"

          echo "Done."
