name: CI / sync sentinez/x

permissions:
  contents: write

on:
  push:
    branches:
      - staging
      - main

jobs:
  sync:
    name: Run sync repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git identity
        run: |
          git config --global pull.rebase false
          git config --global rebase.autoStash false
          git config --global merge.strategy ours
          git config user.name "Duc-Hung Ho"
          git config user.email "iduchungho@gmail.com"

      - name: Sync sentinez/x
        env:
          SENZ_GITHUB_TOKEN: ${{ secrets.SENZ_GITHUB_TOKEN }}
        run: |
          NAME="x"
          USERNAME="kyerans"
          TOKEN="${SENZ_GITHUB_TOKEN}"
          REMOTE="https://${USERNAME}:${TOKEN}@github.com/sentinez/${NAME}.git"
          REMOTE_SAFE="https://github.com/sentinez/${NAME}.git"

          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          PREFIX="staging/src/github.com/sentinez/${NAME}"
          BRANCH="$CURRENT_BRANCH"

          echo "MODULE: $NAME"
          echo "REMOTE: $REMOTE_SAFE"
          echo "PREFIX: $PREFIX"
          echo "BRANCH: $BRANCH"
          echo

          echo "Splitting subtree..."
          SUBTREE_SHA=$(git subtree split --prefix="$PREFIX" "$BRANCH")
          echo "Subtree SHA: $SUBTREE_SHA"

          git config --unset-all http.https://github.com/.extraheader
          git fetch "$REMOTE" "$BRANCH":"tmp_remote" || true

          if git rev-parse --verify tmp_remote >/dev/null 2>&1; then
            echo "Merging remote history (ours strategy)..."
            git merge -s ours tmp_remote -m "Merge remote branch $BRANCH (history only, keep subtree)" --allow-unrelated-histories
          fi

          echo "Force pushing subtree to $REMOTE_SAFE (branch: $BRANCH)..."
          git push "$REMOTE" "$SUBTREE_SHA:$BRANCH" --force

          git branch -D tmp_remote || true

          echo "Subtree sync complete."
