// Copyright 2026 Duc-Hung Ho.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sentinez/cdn/rule/v1/cdn.proto

package rulepb

import (
	v1 "github.com/sentinez/sentinez/api/proto/sentinez/secure/rule/v1"
	v11 "github.com/sentinez/sentinez/api/proto/sentinez/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Expr          *v1.Expression         `protobuf:"bytes,4,opt,name=expr,proto3" json:"expr,omitempty"`
	Status        v11.Status             `protobuf:"varint,6,opt,name=status,proto3,enum=sentinez.types.v1.Status" json:"status,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_sentinez_cdn_rule_v1_cdn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_cdn_rule_v1_cdn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_sentinez_cdn_rule_v1_cdn_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rule) GetExpr() *v1.Expression {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *Rule) GetStatus() v11.Status {
	if x != nil {
		return x.Status
	}
	return v11.Status(0)
}

func (x *Rule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Rule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Rule) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CDN struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"` // @gotags: yaml:"enable"
	Rule          *Rule                  `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`      // @gotags: yaml:"rule"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CDN) Reset() {
	*x = CDN{}
	mi := &file_sentinez_cdn_rule_v1_cdn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CDN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDN) ProtoMessage() {}

func (x *CDN) ProtoReflect() protoreflect.Message {
	mi := &file_sentinez_cdn_rule_v1_cdn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDN.ProtoReflect.Descriptor instead.
func (*CDN) Descriptor() ([]byte, []int) {
	return file_sentinez_cdn_rule_v1_cdn_proto_rawDescGZIP(), []int{1}
}

func (x *CDN) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *CDN) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

var File_sentinez_cdn_rule_v1_cdn_proto protoreflect.FileDescriptor

const file_sentinez_cdn_rule_v1_cdn_proto_rawDesc = "" +
	"\n" +
	"\x1esentinez/cdn/rule/v1/cdn.proto\x12\x14sentinez.cdn.rule.v1\x1a$sentinez/secure/rule/v1/engine.proto\x1a\x1dsentinez/types/v1/known.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x02\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\x04expr\x18\x04 \x01(\v2#.sentinez.secure.rule.v1.ExpressionR\x04expr\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.sentinez.types.v1.StatusR\x06status\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"M\n" +
	"\x03CDN\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12.\n" +
	"\x04rule\x18\x02 \x01(\v2\x1a.sentinez.cdn.rule.v1.RuleR\x04ruleBDZBgithub.com/sentinez/sentinez/api/proto/sentinez/cdn/rule/v1;rulepbb\x06proto3"

var (
	file_sentinez_cdn_rule_v1_cdn_proto_rawDescOnce sync.Once
	file_sentinez_cdn_rule_v1_cdn_proto_rawDescData []byte
)

func file_sentinez_cdn_rule_v1_cdn_proto_rawDescGZIP() []byte {
	file_sentinez_cdn_rule_v1_cdn_proto_rawDescOnce.Do(func() {
		file_sentinez_cdn_rule_v1_cdn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinez_cdn_rule_v1_cdn_proto_rawDesc), len(file_sentinez_cdn_rule_v1_cdn_proto_rawDesc)))
	})
	return file_sentinez_cdn_rule_v1_cdn_proto_rawDescData
}

var file_sentinez_cdn_rule_v1_cdn_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sentinez_cdn_rule_v1_cdn_proto_goTypes = []any{
	(*Rule)(nil),                  // 0: sentinez.cdn.rule.v1.Rule
	(*CDN)(nil),                   // 1: sentinez.cdn.rule.v1.CDN
	(*v1.Expression)(nil),         // 2: sentinez.secure.rule.v1.Expression
	(v11.Status)(0),               // 3: sentinez.types.v1.Status
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_sentinez_cdn_rule_v1_cdn_proto_depIdxs = []int32{
	2, // 0: sentinez.cdn.rule.v1.Rule.expr:type_name -> sentinez.secure.rule.v1.Expression
	3, // 1: sentinez.cdn.rule.v1.Rule.status:type_name -> sentinez.types.v1.Status
	4, // 2: sentinez.cdn.rule.v1.Rule.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: sentinez.cdn.rule.v1.Rule.updated_at:type_name -> google.protobuf.Timestamp
	0, // 4: sentinez.cdn.rule.v1.CDN.rule:type_name -> sentinez.cdn.rule.v1.Rule
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sentinez_cdn_rule_v1_cdn_proto_init() }
func file_sentinez_cdn_rule_v1_cdn_proto_init() {
	if File_sentinez_cdn_rule_v1_cdn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinez_cdn_rule_v1_cdn_proto_rawDesc), len(file_sentinez_cdn_rule_v1_cdn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sentinez_cdn_rule_v1_cdn_proto_goTypes,
		DependencyIndexes: file_sentinez_cdn_rule_v1_cdn_proto_depIdxs,
		MessageInfos:      file_sentinez_cdn_rule_v1_cdn_proto_msgTypes,
	}.Build()
	File_sentinez_cdn_rule_v1_cdn_proto = out.File
	file_sentinez_cdn_rule_v1_cdn_proto_goTypes = nil
	file_sentinez_cdn_rule_v1_cdn_proto_depIdxs = nil
}
