# SecAuditEngine RelevantOnly
# SecAuditLog ./_audit/log/coraza-spoa/audit.log
# SecAuditLogParts ABCFHZ
# SecAuditLogType Serial
# SecAuditLogDir ./_audit/log/coraza-spoa/audit/
# SecAuditLogFormat JSON
# SecAuditLogDirMode 0600
# SecAuditLogFileMode 0600

SecRule TX:BLOCKING_INBOUND_ANOMALY_SCORE "@ge 1" \
"id:999999,\
    phase:5,\
    log,\
    auditlog,\
    msg:'Block score: %{TX.BLOCKING_INBOUND_ANOMALY_SCORE}, threshold: %{tx.inbound_anomaly_score_threshold}',\
    severity:NOTICE,\
    tag:'anomaly/score',\
    setvar:'tx.msg=%{rule.msg}',\
    pass"